### ISSUE TITLE
Unable to retrieve for attributes using AdAccount.getInsights().requestField()

### ISSUE THREAD

**Issue by xyuan14** [facebook/facebook-java-business-sdk#110]
I'm unable to retrieve those fields 

delivery (or delivery_info)
result_rate
results
cost_per_result

by using AdAccount.getInsights().requestField()

It will report the error: 
{
   "error": {
      "message": "(#100) delivery, result_rate, results, cost_per_result are not valid for fields param. please check https://developers.facebook.com/docs/marketing-api/reference/ads-insights/ for all valid values",
      "type": "OAuthException",
      "code": 100,
      "fbtrace_id": "AiibbvLHAZG"
   }
}

code snippet:
```
APINodeList<AdsInsights> adsInsights =  new AdAccount(ad_account_id, context)
                .getInsights()
                .setLevel(AdsInsights.EnumLevel.VALUE_AD)
                .setFiltering("[{\"field\":\"impressions\",\"operator\":\"GREATER_THAN\",\"value\":\"0\"}]")
//                .setBreakdowns(List<AdsInsights.EnumBreakdowns.VALUE_>)
                .setBreakdowns(breakdowns)
                .setTimeRange("{\"since\":\"2017-09-10\",\"until\":\"2017-09-12\"}")
                //These attributes are available
.requestField("account_id")
                .requestField("account_name")
                .requestField("ad_name")
                .requestField("adset_id")
                .requestField("adset_name")
                .requestField("ad_id")
                .requestField("actions")
....
                //These will arise error "is not valid for fields param"
                .requestField("delivery")
                .requestField("result_rate")
                .requestField("results")
                .requestField("cost_per_result")
                .execute();
```

Am I using the right library?

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
