### ISSUE TITLE
How to get the breakdown by day?

### ISSUE THREAD

**Issue by xyuan14** [facebook/facebook-java-business-sdk#111]
I'm supposed to add the Breakdown BY TIME: DAY, but I didn't find the corresponding value in AdsInsights.EnumBreakdowns. The Sample code I downloaded in facebook marketing api page(not here) actually does not work. 

This is the sample code:
```
new AdAccount(ad_account_id, context).getInsights()
      .setLevel(AdsInsights.EnumLevel.VALUE_AD)
      .setFiltering("[{\"field\":\"impressions\",\"operator\":\"GREATER_THAN\",\"value\":\"0\"}]")
      .setBreakdowns(List<AdsInsights.EnumBreakdowns>.VALUE_["DAYS_1"])
      .setTimeRange("{\"since\":\"2017-08-13\",\"until\":\"2017-09-12\"}")
      .requestField("cost_per_result")
```

Does this sdk support breakdown by day? Thanks a lot!

**Comment by jerry80409** [comment]
Hi, there.
https://github.com/facebook/facebook-java-ads-sdk/blob/8943545fb7b67edc452e3e0d471f19a686421dd8/src/main/java/com/facebook/ads/sdk/AdAccount.java#L8632

The `time_increment` can have one result set for each N-day period specified by this param.

Reference by marketing API doc - https://developers.facebook.com/docs/marketing-api/insights/parameters?locale=en_US

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
