### ISSUE TITLE
Raw PII type is invalid for Facebook User ID (uid)

### ISSUE THREAD

**Issue by ngocketit** [facebook/facebook-java-business-sdk#114]
Hi,

I'm trying to automate the adding/removing of custom audience users with Facebook ads SDK and got an error when trying to use Facebook user ID (uid) as the user data. Here is a sample payload that's sent to Facebook:

`{"schema":["UID"],"data":[["some_uid"],["some_uid"]]}`

This payload, however, results in an exception:

`Caused by: com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#100) Raw PII type is invalid, it should be one of EXTERN_ID,EMAIL,PHONE,GEN,DOBY,DOBM,DOBD,LN,FN,FI,CT,ST,ZIP,MADID,COUNTRY,PARTIALPHONE,PHONEID,STREETNAME,STREETNUM,STREETTYPE,STREET2ROW,STREETADDRESS,APPUID,PAGEUID,F5FIRST,F5LAST,EMAIL_MD5,PHONE_MD5","type":"OAuthException","code":100,"fbtrace_id":"CSzBVBbQIGC"}}`

As it's stated on this page, https://www.facebook.com/business/help/381385302004628, Facebook User ID should be supported as custom audience user data. So is it a bug of the SDK?

**Comment by taranjitSinghQ** [comment]
did you get any solution for this? I am facing the same issue

**Comment by TheJacobKim** [comment]
I am still having the same issue. Did you guys find any solution for this issue?

**Comment by nitin-aika** [comment]
I am also having the same issue. Bindings UID + Email throwing this error. Any solution then please update.

**Comment by TheJacobKim** [comment]
@nitin-aika I was able to fix this in `facebook-python-business-sdk`. I am not sure about Java SDK, but I assume you can use a similar logic to fix the issue in Java SDK.  
This [pull request](https://github.com/facebook/facebook-python-business-sdk/pull/547/commits/3bdba13e93064dc4012aadc64fb2903073e0cfed
) was my attempt to fix this issue, then Facebook [merged it](https://github.com/facebook/facebook-python-business-sdk/commit/ac390147132101763a99a917bb59bdc8a374a7ce).

**Comment by sandipwani-webonise** [comment]
> Hi,
> 
> I'm trying to automate the adding/removing of custom audience users with Facebook ads SDK and got an error when trying to use Facebook user ID (uid) as the user data. Here is a sample payload that's sent to Facebook:
> 
> `{"schema":["UID"],"data":[["some_uid"],["some_uid"]]}`
> 
> This payload, however, results in an exception:
> 
> `Caused by: com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#100) Raw PII type is invalid, it should be one of EXTERN_ID,EMAIL,PHONE,GEN,DOBY,DOBM,DOBD,LN,FN,FI,CT,ST,ZIP,MADID,COUNTRY,PARTIALPHONE,PHONEID,STREETNAME,STREETNUM,STREETTYPE,STREET2ROW,STREETADDRESS,APPUID,PAGEUID,F5FIRST,F5LAST,EMAIL_MD5,PHONE_MD5","type":"OAuthException","code":100,"fbtrace_id":"CSzBVBbQIGC"}}`
> 
> As it's stated on this page, https://www.facebook.com/business/help/381385302004628, Facebook User ID should be supported as custom audience user data. So is it a bug of the SDK?

Check your schema, it should be in CAPS Format always.
