### ISSUE TITLE
AdInsights 'account_currency' fields is not present 

### ISSUE THREAD

**Issue by ablejohnson1** [facebook/facebook-java-business-sdk#116]
I am referring to this API documentation. I am trying to fetch the adset insights through java sdk
Following is the code snippet 
`String accessToken = "XXX";
		APIContext context = new APIContext(accessToken).enableDebug(true);
		List<String> fields= Arrays.asList(new String[]{
				"clicks",
				"adset_id",
				"adset_name",
				"reach",
				"impressions",
				"spend",
				"account_currency"
		});
		APINodeList<AdsInsights> adsInsights = new AdAccount("XXXXX", context).
				getInsights()
				.setLevel(AdsInsights.EnumLevel.VALUE_ADSET).requestFields(fields).execute();
		System.out.println(adsInsights.get(0).getFieldAccountId());`

the API response I am getting is 
`Response:
{"data":[{"clicks":"19","adset_id":"XXXXX","adset_name":"Test_041017","reach":"39","impressions":"272","spend":"95.29","account_currency":"INR","date_start":"2017-09-26","date_stop":"2017-10-25"}],"paging":{"cursors":{"before":"MAZDZD","after":"MAZDZD"}}}`

But when I print the object 

[Object]{"adset_id":"XXX","adset_name":"Test_041017","clicks":"19","date_start":"2017-09-26","date_stop":"2017-10-25","impressions":"272","reach":"39","spend":"95.29"}`

I can not find the field for account_currency in the AdsInsights class or I can not find any getter and setter for this field

**Comment by ablejohnson1** [comment]
.

**Comment by ablejohnson1** [comment]
Any updates here?

**Comment by confessin** [comment]
I am facing the same issue, no breakdown fields available as well. 
#122

**Comment by confessin** [comment]
Any updates here? This is important because we need to upgrade our API.

**Comment by confessin** [comment]
One hack for this is to get the raw string, create a json object and get the value you want.
JSONObject rawReportRow = new JSONObject(adInsight.getRawResponse());
String hour = rawReportRow.getString("hourly_stats_aggregated_by_advertiser_time_zone");

**Comment by htch** [comment]
```
    APIRequest.changeRequestExecutor(new APIRequest.DefaultRequestExecutor() {
      override def sendPost(apiUrl: String, allParams: java.util.Map[String,Object], context: APIContext): String = {
        val response = super.sendPost(apiUrl, allParams, context)
        // https://github.com/facebook/facebook-java-ads-sdk/blob/c5e63725d151adc61056799aba10107747b6ddac/src/main/java/com/facebook/ads/sdk/AdsInsights.java
        // sadly there is no way to get values for individual breakdowns from this class atm
        // dirty hack to masquarade breakdown values as different fields:
        response
          .replace("\\\"gender\\\":", "\\\"cpc\\\":").replace("\\\"age\\\":", "\\\"cpm\\\":")
          .replace("\\\"publisher_platform\\\":", "\\\"cpc\\\":").replace("\\\"platform_position\\\":", "\\\"cpm\\\":").replace("\\\"impression_device\\\":", "\\\"cpp\\\":")
      }
    })
```

I for one override default API Request Executor to set "fake" field names that have their own accessor, but which I don't need to have in the output for breakdown fields.
