### ISSUE TITLE
AdSet.class

### ISSUE THREAD

**Issue by lorddct** [facebook/facebook-java-business-sdk#123]
v2.11 no longer supports

> full_funnel_exploration_mode
> is_average_price_pacing

which causes a problem that 

> com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#10) The ad account and app id must be whitelisted","type":"OAuthException","code":10,"fbtrace_id":"EQGVbVqipHd"}

This prevents us from retrieving AdSet when using

> AdSet.fetchById(facebookAd.getFacebookAdsetId(),

 apiContext);

**Comment by ablejohnson1** [comment]
I had the same issue and after some googling, I found this issue 
https://developers.facebook.com/bugs/1742934186003204/ 
try removing  "instagram_actor_id" field from requested fields.If you are requesting for all fields this field will be included automatically

**Comment by lorddct** [comment]
Thanks!

**Comment by bdiesenhaus** [comment]
This also happens if you use AdSet.requestAllFields()

**Comment by Balineni** [comment]
It fails for me because of the field "best_creative".

**Comment by maxkremer** [comment]
This should be re-opened. requestAllFields is a convenience method, having to request all the fields (except the one or two that throw this error) explicitly is crap.

**Comment by dougwithseismic** [comment]
Fails for me when the field 'full_funnel_exploration_mode' is queried

**Comment by debedb** [comment]
@maxkremer wouldn't a few calls to requestField("foo", false) do it instead?

**Comment by galinator9000** [comment]
I'm using the Node SDK, but removing the fields instagram_actor_id and full_funnel_exploration_mode fixed this for me.
