### ISSUE TITLE
Deprecated API version

### ISSUE THREAD

**Issue by mohamedimli** [facebook/facebook-java-business-sdk#124]
Hello
I get this error when using the builded jar :

com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.10.","type":"OAuthException","code":2635,"fbtrace_id":"EGGjoCsGFpp"}}

Could you please update the client to reach the new version of the API ?
Many thanks in advance

Regards,
Mohamed

**Comment by ablejohnson1** [comment]
v2.10 deprecated.Update the SDK to 2.11.0 and it will work

**Comment by ArsalanSaleem94** [comment]
how to update the sdk to 2.11.0 ??

**Comment by ablejohnson1** [comment]
If you are using maven update the dependency version to 2.11.0 otherwise download new sourcecode

**Comment by mohamedimli** [comment]
Thanks !
