### ISSUE TITLE
How to create a product catalog in 2.11? Business::createProductCatalog disappeared

### ISSUE THREAD

**Issue by wjur** [facebook/facebook-java-business-sdk#126]
In the v2.11 the createProductCatalog() method on Business disappeared, and I can't find any replacement. Even [DPAExample.java](https://github.com/facebook/facebook-java-ads-sdk/blob/master/examples/DPAExample.java#L81) uses the non-existing method.

How to create a ProductCatalog in 2.11?

**Comment by bdiesenhaus** [comment]
Any answers to this question?

**Comment by wjur** [comment]
The issue persists. No answers yet 👎

**Comment by Jayanth7778** [comment]
I too have the same issue. Can anyone please help me.....

**Comment by jtermaat** [comment]
Is this being addressed by anyone?  Is it a confirmed bug? The documentation says this method should still be available in 2.11.  It's causing problems for our organization, and we would be very appreciative if this was fixed or a workaround explained.
