### ISSUE TITLE
How to get 3 second video views

### ISSUE THREAD

**Issue by manssa01** [facebook/facebook-java-business-sdk#128]
Hello,

Hello,
I am trying to use JAVA-ads-SDK  to get some metrics, I got the majority but the "3 second video views" is missing, here is my code:

import com.facebook.ads.sdk.APIContext;
import com.facebook.ads.sdk.APIException;
import com.facebook.ads.sdk.APINodeList;
import com.facebook.ads.sdk.APIRequest;
import com.facebook.ads.sdk.Ad;
import com.facebook.ads.sdk.AdAccount;
import com.facebook.ads.sdk.AdSet;
import com.facebook.ads.sdk.AdsActionStats;
import com.facebook.ads.sdk.AdsInsights;
import com.facebook.ads.sdk.Campaign;
import com.restfb.Connection;
import com.restfb.json.JsonObject;
import com.restfb.types.Insight;
import java.util.Iterator;
import java.util.List;

/**
*

@author manssa01
*/

public static void main(String[] args) throws APIException {
APIContext("********************************************************************************************");
try {
APIRequest request = new APIRequest<>(context, "me", "/adaccounts", "GET", AdAccount.getParser());
APINodeList accounts = (APINodeList)(request.execute());
for (AdAccount account : accounts) {
APINodeList campaigns = new AdAccount( account.getId(), context).getCampaigns().requestAllFields()
.execute();
for (Campaign campaign : campaigns) {
APINodeList adSets = new Campaign( campaign.getId(), context).getAdSets().requestAllFields()
.execute();
for (AdSet adset : adSets) {

      APINodeList<Ad> ads = new AdSet( adset.getId(), context).getAds().requestAllFields()
.execute();

      for (Ad ad:ads) {
           APINodeList<AdsInsights> adInsights = new Ad(ad.getId(), context).getInsights().requestField("what to write here")
.execute();
for (AdsInsights adInsight : adInsights) {
d.APIRequestGetInsightsAsync insightsAsync = new Ad(adId, context).getInsightsAsync();
 AdReportRun report = insightsAsync
	.requestField("account_name")
.requestField("impressions")
 .requestField("spend")
 .requestField("reach")
 .requestField("total_actions")
	.requestField("clicks")
.requestField("total_video_views")
	.requestField("cpc")
	.requestField("cost_per_action_type")
	.requestField("cost_per_unique_click")
    .requestField("cpm")
       .requestField("video_10_sec_watched_actions")
     .requestField("video_30_sec_watched_actions")
 .requestField("video_p100_watched_actions")
   .requestField("video_p95_watched_actions")
 .requestField("video_p75_watched_actions")
 .requestField("video_p50_watched_actions")
 .requestField("video_p25_watched_actions")
.execute()
	.head();
while (report.fetch().getFieldAsyncPercentCompletion() != 100) {
	try {
	Thread.sleep(6000);
	} catch (InterruptedException e) {

	}

            }
            }
           
      }
    }  
    }
} catch (Exception e) {
e.printStackTrace();
}
}

}

**Comment by alex-b** [comment]
Hey there,

You could try the "page_video_views" field.
"Total number of times page's videos have been viewed for more than 3 seconds."

**Comment by mcoirad-gmmb** [comment]
I'm pretty sure that isn't a field in the Ad Insights API. Could you link to documentation?

**Comment by alex-b** [comment]
> I'm pretty sure that isn't a field in the Ad Insights API. Could you link to documentation?

https://developers.facebook.com/docs/graph-api/reference/v3.2/insights#videoviews

**Comment by mcoirad-gmmb** [comment]
Thanks for the quick reply a year later!
I think the doc you linked is for page insights, not ad insights.

For reference, I ended up finding "video_views" under <Ad Actions Stats> -> <Action Type> here:
https://developers.facebook.com/docs/marketing-api/reference/ads-action-stats/
