### ISSUE TITLE
Adding users to Custom Audience is not working

### ISSUE THREAD

**Issue by osvadimos** [facebook/facebook-java-business-sdk#129]
Adding users through
 `CustomAudience.APIRequestCreateUser request = customAudience.createUser()
  request.setPayload(payload.toString())
  request.execute()`
So it's adding users ok, but then Custom Audience is showing **audience is too small**

**Comment by asmaliaks** [comment]
> Adding users through
CustomAudience.APIRequestCreateUser request = customAudience.createUser() request.setPayload(payload.toString()) request.execute()
So it's adding users ok, but then Custom Audience is showing audience is too small

I've got the same issue
