### ISSUE TITLE
Facebook Ads SDK :Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground() 

### ISSUE THREAD

**Issue by manishmips28** [facebook/facebook-java-business-sdk#132]
I have seen this issue reported before but closed issue so I am posting it .I am getting above error while showing ads like Banner and Native in my application.When I am increasing number of ads(Native ads) in list this error frequency increases.Please suggest what should I do?
following is crash logs.

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground() at android.os.AsyncTask$3.done(AsyncTask.java:330) at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354) at java.util.concurrent.FutureTask.setException(FutureTask.java:223) at java.util.concurrent.FutureTask.run(FutureTask.java:242) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) at java.lang.Thread.run(Thread.java:776) Caused by java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.v3mobi.first.cut/databases/ads.db at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55) at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:547) at com.facebook.ads.internal.e.d$2.a(Unknown Source) at com.facebook.ads.internal.e.d$2.b(Unknown Source) at com.facebook.ads.internal.e.d$1.a(Unknown Source) at com.facebook.ads.internal.e.d$1.doInBackground(Unknown Source) at android.os.AsyncTask$2.call(AsyncTask.java:316) at java.util.concurrent.FutureTask.run(FutureTask.java:237) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) at java.lang.Thread.run(Thread.java:776)

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
