### ISSUE TITLE
Bean class generation for SavedAudience 

### ISSUE THREAD

**Issue by shukla2009** [facebook/facebook-java-business-sdk#134]
As of now, there is no way in SDK to fetch saved audience directly. Is it feasible to generate that class same as CustomAudience 

api call : https://graph.facebook.com/v2.11/<saved_aud_ids>?access_token=<token>&appsecret_proof=<proof>& fields=id,description,name...

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
