### ISSUE TITLE
Fetching SavedAudience for ad account

### ISSUE THREAD

**Issue by shukla2009** [facebook/facebook-java-business-sdk#135]
SDK doesn't provide any way to fetch SavedAudience for the ad account 
API call :  https://graph.facebook.com/v2.11<act_id>/saved_audiences?access_token=<token>&appsecret_proof=<proof>

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
