### ISSUE TITLE
The sample code in README seems to refer to an older version (?)

### ISSUE THREAD

**Issue by joseenieto** [facebook/facebook-java-business-sdk#138]
Hi,

As a Java Ads SDK newbie, I first tried to run the example in the README file ("Run Sample code" section), but the compilation failed. I had to correct a few things in order to make it work. I would like to check with you if the following amendments are correct (my feeling is that the sample code may probably be referring to an older version of the library):

**a, b) Original:**
`import com.facebook.ads.sdk.AdAccount.EnumCampaignStatus;`
`import com.facebook.ads.sdk.AdAccount.EnumCampaignObjective;`
**My proposal:** 
`import com.facebook.ads.sdk.Campaign.EnumStatus;`
`import com.facebook.ads.sdk.Campaign.EnumObjective;`
**Why?** I got the error "error: cannot find symbol". Indeed, I have checked that these enumerations are defined as part of Campaign, not AdAccount. I suppose the original code is referring to a previous version of the library.

**c) Original:**
`public static final Long ACCOUNT_ID = [Your account ID];`
**My proposal:**
`public static final String ACCOUNT_ID = "[Your account ID]";`
**Why?** It can happen that a valid Account ID is longer than the biggest valid Long number, and you will get a "error: integer number too large". I have thought that the simpler way to avoid this problem is just to use a String instead (the constructor of AdAccount can also accept Account ID as a string).

My apologies in case I am wrong. I would much appreciate your comments in that case. Otherwise, I would suggest to update the example in the README file.

Thanks in advance for your feedback!

JE

**Comment by samsonych** [comment]
Added an appropriate pull request to fix the given issue - https://github.com/facebook/facebook-java-business-sdk/pull/273
