### ISSUE TITLE
Adding several requests to BatchRequest

### ISSUE THREAD

**Issue by juanmbellini** [facebook/facebook-java-business-sdk#141]
Is there any change to add an addAll(Collection<ApiRequest>) method to the BatchRequest class? It would be great to add several requests to a batch without having to iterate though a collection, doing it for each element of it.
For example, I would use it like this:
```
final Collection<ApiRequest> requests = getRequests();
final BatchRequest batchRequests = new BatchRequest(apiContext);
batchRequest.addAll(requests);
batchRequest.execute();
```
Thank you very much.

**Comment by wei-fb** [comment]
Thanks for reporting the Ads API SDK bug! You are requesting a new feature for Ads API SDK. We have heard your ask and will consider adding this feature in later versions.
