### ISSUE TITLE
How to set the rule of a PromotedObject?

### ISSUE THREAD

**Issue by libbysharf** [facebook/facebook-java-business-sdk#146]
Hi,
In the Graph API, I can set the pixel_rule of the promoted_object.
Is there a way to do this in java? I don't see this field in the PromotedObject class

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
