### ISSUE TITLE
How to set an ad's trackingtag?

### ISSUE THREAD

**Issue by libbysharf** [facebook/facebook-java-business-sdk#147]
Hi,
Is there a way to do this in java? I don't see any TrackingTag class...
https://developers.facebook.com/docs/marketing-api/click-tags

curl \
  -F 'url=https://www.mytagprovider.com' \
  -F 'add_template_param=1' \
  -F 'access_token=<ACCESS_TOKEN>' \
  https://graph.facebook.com/v2.11/<AD_ID>/trackingtag

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
