### ISSUE TITLE
getKeywordStats() not working

### ISSUE THREAD

**Issue by moisestg** [facebook/facebook-java-business-sdk#148]
I'm trying to retrieve stats for each of the interests used in the targeting of a specific ad (as described in https://developers.facebook.com/docs/marketing-api/reference/ad-keyword-stats). When trying the call in [Graph Explorer](https://developers.facebook.com/tools/explorer/?method=GET&path=ad_id%2Fkeywordstats&version=v2.11) it works perfectly but I get an empty response in Java. I have already used the SDK to get insights for campaigns, ad sets and ads so the general setup is working. This is the code I have for now:

```java
APINodeList<AdKeywordStats> stats = new Ad(adId, CONTEXT).getKeywordStats()
    .requestAllFields().execute();    
System.out.println(stats);
```

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
