### ISSUE TITLE
Move to marketing API v2.11

### ISSUE THREAD

**Issue by shaymolho** [facebook/facebook-java-business-sdk#150]
Hi,

We got a warning from facebook saying all API prior to 2.11 is deprecated since May 8, 2018.

This SDK need to change work with the new api version, otherwise all the clients will stop working.

**Comment by ellentao** [comment]
Hi,

Thanks for your comment! Actually v2.11 will be deprecated on January 30, 2020(see https://developers.facebook.com/docs/graph-api/changelog). Besides, FB will release a new version SDK, together with v2.13 API update. That will definitely happen before the deprecation of v2.11 API. Don't worry :)

**Comment by matthull** [comment]
It's important to note that apparently the Facebook Marketing API follows a different (more aggressive) deprecation schedule than Graph API. Details here: https://developers.facebook.com/docs/marketing-api/versions

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
