### ISSUE TITLE
creative id preview error?

### ISSUE THREAD

**Issue by kykkyn2** [facebook/facebook-java-business-sdk#151]
AdCreative adPreviews = new AdCreative("creative_id", context);
        APINodeList<AdPreview> list = adPreviews.getPreviews().setAdFormat(AdPreview.EnumAdFormat.VALUE_DESKTOP_FEED_STANDARD).execute();

iframe data click  -> The parameter t is required

what is the t ?

**Comment by ellentao** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
