### ISSUE TITLE
uploading 3.0.0 to maven?

### ISSUE THREAD

**Issue by jsadn** [facebook/facebook-java-business-sdk#155]
Hi friends,

Who owns deploying new versions to maven? 
The following only has 2.11, but here in the repo we're up to 3.0.0 which we'd love to upgrade to. 
https://mvnrepository.com/artifact/com.facebook.ads.sdk/facebook-java-ads-sdk

**Comment by shootingsyh** [comment]
Hi Try https://mvnrepository.com/artifact/com.facebook.business.sdk/facebook-java-business-sdk We changed the SDK name for 3.0.0
