### ISSUE TITLE
Null pointer exception on AsyncExecutor

### ISSUE THREAD

**Issue by tmihalicka** [facebook/facebook-java-business-sdk#156]
I'm trying use new 3.0 SDK in Scala but i have problem when i want to call `getInsightsAsync` on AdAcount object this call returns **null pointer exceltion**

This coused because AsyncExecutor is not created: 

```SCALA
    val adAccountFutureList = config.adAccount.accounts.map { acc =>
      val addAccount = new AdAccount(acc.id, facebookContext).getInsightsAsync
        .setLevel(config.adAccount.level)
        .setFields(config.adAccount.fields.mkString(","))
        .executeAsync()
        .asScala //deal with facebook shitty promise

      addAccount
    }
```

I found solution define AsyncExecutor via static call:
```SCALA
APIRequest.changeAsyncRequestExecutor(new DefaultAsyncRequestExecutor())
```

This is definition in ApiRequest.java

```JAVA
  private static IRequestExecutor executor = new DefaultRequestExecutor();
  private static IAsyncRequestExecutor asyncExecutor = null;
```

This is desired behaviour?

Because in example i cannot find any reference to explicitly set `DefaultAsyncRequestExecutor`.

**Comment by shootingsyh** [comment]
You are right. We will update the example code to initialize the async request executor. We didn't do that when initialize the APIRequest because async executor is heavy. We don't want user who doesn't use async call to take the cost.
