### ISSUE TITLE
nextPage() failing on empty ({"data":[]}) response

### ISSUE THREAD

**Issue by myshinyemail** [facebook/facebook-java-business-sdk#157]
nextPage() fails when Facebook returns `{"data":[]}`.

(This is probably because Facebook returns a paging->cursors->after identifier - despite there being no further data available - at one time I expect the "after" field was empty in this case.)

The error occurs at APINode line 113, viz:
JsonObject paging = obj.get("paging").getAsJsonObject();

Other places with similar functions (e.g., AdAccount line 285/286) perform a check to ensure the paging field exists - this appears to have been omitted in the case of APINode.

**Comment by shootingsyh** [comment]
Duplicate of #154
