### ISSUE TITLE
.getInsightsAsync on AdAcount not working

### ISSUE THREAD

**Issue by tmihalicka** [facebook/facebook-java-business-sdk#158]
Hello, i have problem with async downloading of AdInsights data. On version 2.11 this functionality properly working. Every spawned jobs returns information about asynchronus completition. Now this information is null.

Can be this problem caused by using AsyncExecutor on job?

I have this code bellow for polling data on AdReportRun object: 

```SCALA
  implicit class AdReportRunImplicits(report: AdReportRun) {

    def poll(timeout: Duration): Task[AdReportRun] = {
      def recursive(taskReport: Task[AdReportRun]): Task[AdReportRun] =
        taskReport.flatMap {
          case r if r.fetch().getFieldAsyncPercentCompletion == 100 => taskReport
          case r => recursive(Task.schedule(r, timeout))
        }

      recursive(Task.now(report))
    }
  }
```

Method 

```JAVA
getFieldAsyncPercentCompletion // return null before 3.0.0 return Long with progress
```
return always null.

This is console output bellow:

```TEXT
========Start of Async API Call========
========Start of Async API Call========
========Start of Async API Call========
18/05/14 14:23:21 INFO FacebookDownloadJob: SparkJob completed after 5 seconds
18/05/14 14:23:21 INFO OkHttpClient: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
18/05/14 14:23:21 INFO OkHttpClient: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
18/05/14 14:23:21 INFO OkHttpClient: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Response:
{"report_run_id":"1997504617244527"}
========End of API Call========
[Warning] When parsing response, object is not consistent with JSON:
[JSON]{"report_run_id":"1997504617244527"}
[Object]{}
Response:
{"report_run_id":"254699821753261"}
========End of API Call========
[Warning] When parsing response, object is not consistent with JSON:
[JSON]{"report_run_id":"254699821753261"}
[Object]{}
Response:
{"report_run_id":"235597417023179"}
========End of API Call========
[Warning] When parsing response, object is not consistent with JSON:
[JSON]{"report_run_id":"235597417023179"}
[Object]{}
```

There is also deserialization Warning: **[Warning] When parsing response, object is not consistent with JSON:**

**Comment by smahmood2554** [comment]
I have a similar problem, I am using python SDK and when doing an async call to get insights the call just stalls and does not return anything. It used to work fine before the upgrade to v.3.0.

**Comment by tmihalicka** [comment]
Yeah, at version 2.11 works this in java sdk also. But version 3.0 contains lots of bugs and misleading examples. It's really shame for Facebook release library like this one.

**Comment by dothunguyen** [comment]
I am trying out this SDK and having the same problem.
After going through their samples, I found the answer,. We need to call fetch() to actually retrieve job status, then get the field values as usual
