### ISSUE TITLE
(#2654) Unsupported operator: The operator operator is not supported

### ISSUE THREAD

**Issue by DanyalAdfenix** [facebook/facebook-java-business-sdk#161]
I am trying to create a custom audience in version 3.0 but it gives me this error  
`{
	"error": {
		"message": "(#2654) Unsupported operator: The operator operator is not supported",
		"type": "OAuthException",
		"code": 2654,
		"error_subcode": 1713032,
		"fbtrace_id": "AuOG4SSsJaH"
	}
}`

but when I try this on the graph api explorer and it works fine there. This is the json of my rule.
`{
	"inclusions": {
		"operator": "or",
		"rules": [
			{
				"event_sources": [
					{
						"id": "someId",
						"type": "pixel"
					}
				],
				"retention_seconds": 8400,
				"filter": {
					"operator": "and",
					"filters": [
						{
							"field": "domain",
							"operator": "i_contains",
							"value": "someDomain"
						}
					]
				}
			}
		]
	}
}`

**Comment by ellentao** [comment]
Hey,
Thanks for your comment! This is actually a version change in v3.0. You could take a look at our latest changelog. If you believe the changelog is unclear please report the it on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/

**Comment by DanyalAdfenix** [comment]
I am doing the same using java SDK but getting the above error and when I use it directly on graph API it works fine.

**Comment by mychalvlcek** [comment]
Hi @DanyalAdfenix i just going through the same situation and i find following works (for custom audience EP)

```
APINodeList<CustomAudience> audiences = new AdAccount(accountId, fbContext)
                    .getCustomAudiences()
                    .requestFields(Arrays.asList("id", "name", "subtype"))
                    .setFiltering("[{field:\"subtype\",operator:\"EQUAL\",value:\"asdf\"}]")
                    .execute();
```
