### ISSUE TITLE
implement the spliterator for ads insights to support auto pagination or dont extend ArrayList

### ISSUE THREAD

**Issue by convoi** [facebook/facebook-java-business-sdk#162]
treat this as pseudo code please:
```
public void processAll(AdReportRun adReportRun) {
  APINodeList<AdsInsights> result  = adReportRun.getInsights().execute().withAutoPaginationIterator(true);
  List<AdsInsights> spliteratorList = result.stream().collect(Collectors.toList());
  List<AdsInsights> iteratorList = new ArrayList<>();
  for(AdsInsights adsInsights: result) iteratorList.add(adsInsights);
  assert(iteratorList.size() == spliteratorList.size()); // will fail if the list is bigger than a single page
}
```
since APINodeList extends ArrayList, you get a spliterator by default which works optimized for ArrayList.
but since you overwrite the iterator() you  get the weird behavior that the iterator is making consecutive page requests, while the spliterator (and thus the stream api) does not.

Many people nowadays are using java 8+ and have access to the stream api.
If you provide your own list class which extends ArrayList please make it adhere to the contract.
size() should report the real size of the list and not the first page only.
stream() should allow iteration in the same way as iterator does.

Another idea would be: don't extend the ArrayList but use a delegate.

**Comment by vicdus** [comment]
This feature will be available in next release.
