### ISSUE TITLE
nextPage() method return java.lang.NoSuchMethodError: com.facebook.ads.sdk.APIRequest.setOverrideUrl(Ljava/lang/String;)V

### ISSUE THREAD

**Issue by yaffam** [facebook/facebook-java-business-sdk#167]
When calling the nextPage() method on 'APINodeList', the next exception is thrown in v3.0.2 ,
in v2.11 It did not happen
java.lang.NoSuchMethodError: com.facebook.ads.sdk.APIRequest.setOverrideUrl(Ljava/lang/String;)V
	at com.facebook.ads.sdk.APINodeList.nextPage(APINodeList.java:87)
	at com.facebook.ads.sdk.APINodeList.nextPage(APINodeList.java:60)
what to do ?

**Comment by vicdus** [comment]
Hey yaffam. Can you provide a snip of code to reproduce this exception?

**Comment by yaffam** [comment]
APINodeList<AdsInsights> insightCampNL = null;
     insightCampNL = adreport.getInsights().execute();
     if (!insightCampNL.isEmpty()) {
            insightCampNL = insightCampNL.withAutoPaginationIterator(true);
         for (AdsInsights insightCamp : insightCampNL) {
                                      System.out.println("insightCamp.getFieldCampaignId()=>" +
                                       insightCamp.getFieldCampaignId());
          }
       }

in for row , I get this exception

**Comment by yaffam** [comment]
Exception in thread "main" java.lang.NoSuchMethodError: com.facebook.ads.sdk.APIRequest.setOverrideUrl(Ljava/lang/String;)V
	at com.facebook.ads.sdk.APINodeList.nextPage(APINodeList.java:87)
	at com.facebook.ads.sdk.APINodeList.nextPage(APINodeList.java:60)
	at com.facebook.ads.sdk.APINodeList$APINodeListAutoPaginationIterator.hasNext(APINodeList.java:161)
	at d.co.il.facebookutils.impl.GetFacebookReportImpl.getAllCampaignInsights(GetFacebookReportImpl.java:222)

**Comment by vicdus** [comment]
How was your dependency is installed(maven or compiled by yourself), and what's your JDK version?

**Comment by yaffam** [comment]
i download facebook-java-business-sdk-3.0.2-jar-with-dependencies.jar
from
https://repo1.maven.org/maven2/com/facebook/business/sdk/facebook-java-business-sdk/3.0.2/

**Comment by vicdus** [comment]
I cannot reproduce the same error... Maybe it is related to jar file problem. Would you please try:
1. Check if you are using jdk 1.8 for both compile and run. Some IDE can have different version for them.
2. Rebuild you project completely(maybe delete your ./target folder, depend on your build tool)
3. If you are using maven, add this to the dependencies to install sdk
`   
 <dependency>
      <groupId>com.facebook.business.sdk</groupId>
      <artifactId>facebook-java-business-sdk</artifactId>
      <version>3.0.2</version>
</dependency>
`

If this problem persists, please contact us :)

**Comment by yaffam** [comment]
1.I'm using in jdk 1.7 for both (in ver 2.11 all run fine).
2. rebuild didn't help 
3. I'm not using  maven, I download this jar file.
can you reproduce with jdk 1.7 ?
