### ISSUE TITLE
Problems with APINode implementations

### ISSUE THREAD

**Issue by felipeAndrade0918** [facebook/facebook-java-business-sdk#168]
Right now, on the master branch, the _parseResponse_ method has a return type of **APINodeList&lt;APINode&gt;**.
Let's take the **Ad** class for example, the return type of the overwritten method above is **APINodeList&lt;Ad&gt;**.
This is giving me the following error:

> The return type is incompatible with APINode.parseResponse(String, APIContext, APIRequest&lt;APINode&gt;)

This change was introduced on the commit **2fb8b65b6b61c85d90be79e0453727730d83fb63**.

Before this change, the return type for the _parseResponse_  method of **APINode** was simply **APINodeList** and the above was possible. **Ad** class would not have problems.

Am I doing something wrong is it really a bug?

Thanks for your attention!

**Comment by vicdus** [comment]
Hi,

Do you have a sample code to reproduce the error?

Thanks!

**Comment by felipeAndrade0918** [comment]
Let's take the **APINode** _parseResponse_ method:

> public static APINodeList&lt;APINode&gt; parseResponse(String json, APIContext context, APIRequest&lt;APINode&gt; request) throws MalformedResponseException

And now an implementation, in this case the **Ad** class:

> public static APINodeList&lt;Ad&gt; parseResponse(String json, APIContext context, APIRequest request) throws MalformedResponseException

I believe you can't change the return type from APINodeList&lt;APINode&gt; to APINodeList&lt;Ad&gt;, right?

This was no problem in the previous versions. Let's take a look at the **2.11.1** version:

> public static APINodeList parseResponse(String json, APIContext context, APIRequest&lt;APINode&gt; request) throws MalformedResponseException

No generics in the return type, so the **Ad** class with its overwritten method is fine.

**Comment by jalpesh** [comment]
Hi Guys Am facing this issue. Is there a stable branch/commit/tag which I can use?
