### ISSUE TITLE
Asynchronous Batch Requests

### ISSUE THREAD

**Issue by lidox** [facebook/facebook-java-business-sdk#171]
Is there a way to make asynchronous batch requests? The [docs](https://developers.facebook.com/docs/graph-api/asynchronous-batch-requests#example) show some examples using curl only. 

```java 
    BatchRequest batchRequest = new BatchRequest(context);

    // adding some requests
    request.addToBatch(batchRequest1);
    request.addToBatch(batchRequest2);
    request.addToBatch(batchRequest3);

    List<APIResponse> batchResult = batchRequest.execute(); //<-- How to async?

**Comment by gschambial** [comment]
Hi @lidox ,

I need help with the same. Did you find any solution?
