### ISSUE TITLE
Fields missing from SystemUser class

### ISSUE THREAD

**Issue by salunkeganesh93** [facebook/facebook-java-business-sdk#181]
Role field is missing from System User class. Whereas when this call is executed via rest client only fields returned are role, id and name.
This class also contains created_by etc. not sure if those are relevant for system users.

**Comment by nagesh-salunke** [comment]
+1

**Comment by salunkeganesh93** [comment]
Requires attention.

**Comment by Nathaaaalie** [comment]
Hi @salunkeganesh93, we have deprecated this field. Please see the https://developers.facebook.com/docs/marketing-api/reference/system-user/assigned_ad_accounts/, there is no more 'role' in the data table.
