### ISSUE TITLE
Missing "CALL_NOW" Call To Action

### ISSUE THREAD

**Issue by ugarciar** [facebook/facebook-java-business-sdk#182]
Hi, I see that in one of the latest updates "CALL_NOW" Call To Action has been deleted in EnumType class. Instead, "CALL" and "CALL_ME" have been inserted. The problem is when I try to do an store visit creative:

GRAPH_API:
POST: /3.0/act_XXXX/adcreatives

object_story_spec --> {"link_data":{"call_to_action":{"type":"CALL_NOW","value":{"link":"tel:+XXXX"}},"image_hash":"XXXX","link":"www.myLink.com"},"page_id":"XXXX"}
dynamic_ad_voice --> STORY_OWNER

With the Graph API I can make this call, and the creative is created. But with the facebook-java-business-sdk I dont have CALL_NOW in EnumType. If I use, "CALL" or "CALL_ME", the response is error, invalid CTA:
{"message":"Invalid parameter","type":"OAuthException","code":100,"error_subcode":1815260,"is_transient":false,"error_user_title":"Unsupported call to Action","error_user_msg":"The call to action you selected is not supported","fbtrace_id":"DUz2GjtODwj"}

Thanks in advance.

**Comment by jingping2015** [comment]
Thanks for repost this! Is this issue still happen in new version of SDK? If yes, please provide more information. Like what's your SDK call and what's the corresponding Graph API call.

**Comment by adglow-ugarcia** [comment]
Hi, yes its still happens, because there is no Call to Action CALL_NOW yet on the Facebook SDK version 3.2.1.


```
AdAccount account = new AdAccount(ACCOUNT_ID, context);			
AdCreative creative = account.createAdCreative().setDynamicAdVoice(EnumDynamicAdVoice.VALUE_STORY_OWNER)
					.setObjectStorySpec(new AdCreativeObjectStorySpec()
							.setFieldLinkData((new AdCreativeLinkData()
									.setFieldCallToAction(new AdCreativeLinkDataCallToAction()
											.setFieldType(**_EnumType.VALUE_CALL_NOW_**)
									.setFieldValue(new AdCreativeLinkDataCallToActionValue()
											.setFieldLink("tel:34912240111")
									)
									)							
								)
							.setFieldImageHash(IMAGENHASH)
							.setFieldLink("https://www.zara.com/es/")
							)
							.setFieldPageId(PAGEID)
							)
					
					.execute();
```

GRAPH_API:
POST: /3.2/act_XXXX/adcreatives

**object_story_spec** --> {"link_data":{"call_to_action":{"type":"CALL_NOW","value":{"link":"tel:+XXXX"}},"image_hash":"XXXX","link":"www.myLink.com"},"page_id":"XXXX"}

**dynamic_ad_voice** --> STORY_OWNER


As you can see in SDK code, I do not have the EnumType. CALL_NOW and in Graph API I can use it and it works.

With SDK I have to use other CallToAction like CALL or CALL_ME, but these ones fails with same request.

Thanks in advance.

**Comment by jingping2015** [comment]
Hi, `CALL_NOW` should be a valid enum for `AdCreativeLinkDataCallToAction`. But we may need some time to fix this in our side. If this really block you, please fork the code and add this enum here 
 as a temporary solution. https://github.com/facebook/facebook-java-business-sdk/blob/58312d246af94d40620c4d11af1d9ca83feeb887/src/main/java/com/facebook/ads/sdk/AdCreativeLinkDataCallToAction.java#L248

**Comment by adglow-ugarcia** [comment]
Hi, thank you for the feedback, at this moment it's not blocking us, we can wait until it is fixed.
Thank you very much.
Regards

**Comment by adglow-ugarcia** [comment]
No, the issue hasn't been fixed yet.
Thanks
