### ISSUE TITLE
AdCreativeLinkData missing setters in 'mainline'

### ISSUE THREAD

**Issue by kvijayva** [facebook/facebook-java-business-sdk#194]
Hi,
I am from the Social Advertising team in Amazon.

I want to do something similar to [this](https://github.com/facebook/facebook-java-business-sdk/blob/master/examples/src/main/java/com/facebook/ads/sdk/samples/BasicExample.java#L77-L81) example on Github.

However, the [AdCreativeLinkData class in master branch](https://github.com/facebook/facebook-java-business-sdk/blob/master/src/main/java/com/facebook/ads/sdk/AdCreativeLinkData.java) doesn't have any of these setters. For e.g., it doesn't have the `setFieldMessage` or `setFieldLink` methods. (However, note that these setters are indeed present in the same class but [another branch](https://github.com/facebook/facebook-java-business-sdk/blob/577a19fb9c7b103ec76316db710a59fabffcae99/src/main/java/com/facebook/ads/sdk/AdCreativeLinkData.java#L491).)

Please fix on an urgent basis as it is an adoption blocker for the SDK.

Thanks.

**Comment by jingping2015** [comment]
Thanks for reposting this issue, new release should have the fix.
