### ISSUE TITLE
Is this repo still humanly maintained ?

### ISSUE THREAD

**Issue by nicolasdalsass** [facebook/facebook-java-business-sdk#195]
Hi,

Are there people working on this lib, or has its evolution been fully automated ?

The latest releases have broke a lot of types and workflows. (see https://github.com/facebook/facebook-java-business-sdk/issues/194 , https://github.com/facebook/facebook-java-business-sdk/issues/185 for example), while still being flagged as bugfix/minor versions.

I'd open issues for all the types that are currently incorrect, but since no issue has been answered (to the best of my knowledge) since june, the month where all commits became 'auto generated code updates' (which I suppose are automated), I think it's fair to ask the question whether it's worth opening issues ? Is anyone reading them ?

For the curious passerbys here, my personal advice for now is to stick to v3.1.2 which is both enough up to date to latest API changes so that you're not blocked too much and not yet too much broken so that you can still use types in your code !

Best,
Nicolas

**Comment by adglow-ugarcia** [comment]
Hi,
I would really like to know too if there is any human behind this...
My issue is from 13th August (#182 ) and no answer yet.....

Regards,
Unai

**Comment by nicolasdalsass** [comment]
Hi,

Thanks for answering issues again !
