### ISSUE TITLE
AdSet class field has deprecated one on v3.2.1

### ISSUE THREAD

**Issue by tiger154** [facebook/facebook-java-business-sdk#197]
Hi all,

New version of v3.2.1 on AdSet there is a field which is deprecated "is_average_price_pacing"

On the facebook document it says 
 **is_autobid and is_average_price_pacing is deprecated in both GET and POST in v3.0 and later**

And when I got the error when I use requestAllFields() like below

com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#12) is_average_price_pacing is deprecated for versions v3.0 and higher","type":"OAuthException","code":12,"fbtrace_id":"GmC1IiolVdD"}}

So please update the fields section on AdSet Class please

**Comment by tiger154** [comment]
I checked the document for right fields. 
Total 43 fields for AdSet. 

1. Where you need to change 
  - https://github.com/facebook/facebook-java-business-sdk/blob/master/src/main/java/com/facebook/ads/sdk/AdSet.java#L4935 

 2. Fields for v 3.2 

- id
- account_id
- adlabels
- adset_schedule
- attribution_spec
- bid_amount
- bid_info
- bid_strategy
- billing_event
- budget_remaining
- campaign
- campaign_id
- configured_status
- created_time
- creative_sequence
- daily_budget
- daily_min_spend_target
- daily_spend_cap
- destination_type
- effective_status
- end_time
- frequency_control_specs
- instagram_actor_id
- lifetime_budget
- lifetime_imps
- lifetime_min_spend_target
- lifetime_spend_cap
- name
- optimization_goal
- pacing_type
- promoted_object
- recommendations
- recurring_budget_semantics
- rf_prediction_id
- source_adset
- source_adset_id
- start_time
- status
- targeting
- time_based_ad_rotation_id_blocks
- time_based_ad_rotation_intervals
- updated_time
- use_new_app_click

**Comment by jingping2015** [comment]
Thanks for reporting this, we will fix it soon.

**Comment by jingping2015** [comment]
This should be solved in recent release.
