### ISSUE TITLE
AdCreative.requestAllFields() requesting deprecated fields

### ISSUE THREAD

**Issue by tsengjonathan** [facebook/facebook-java-business-sdk#198]
Hi,

Similar to #197: in the latest release (v3.2.1), **.requestAllFields()** is requesting **asset_feed_id** which is deprecated in v3.2 as per the Graph API Changelog: https://developers.facebook.com/docs/graph-api/changelog/version3.2

Under https://github.com/facebook/facebook-java-business-sdk/blob/master/src/main/java/com/facebook/ads/sdk/AdCreative.java#L1511, **asset_feed_id** needs to be removed from the **FIELDS** array or else **.requestAllFields()** is inherently broken right now.

**Comment by jingping2015** [comment]
We should have this issue be fixed in next release. Thanks for reporting this.

**Comment by lbadi** [comment]
@jingping2015 i was using 3.2.0. I just update to 3.2.1 and it's already fixed :) Thanks!

**Comment by jahngergely** [comment]
+1

**Comment by clande** [comment]
This issue also exists in CustomAudience.APIRequestGet.requestAllFields. That is, it is requesting fields that either don't exist or are not allowed for us to request. Should I make a separate issue for this?

**Comment by jingping2015** [comment]
This has been solved in our recent release.
