### ISSUE TITLE
Default scope on AdCreativeVideoData ?

### ISSUE THREAD

**Issue by lbadi** [facebook/facebook-java-business-sdk#199]
Prior to version 3.2 , the class `AdCreativeVideoData` has a public default constructor `AdCreativeVideoData()`. 

In 3.2 the default constructor is no more public but has a default scope making imposible to initialize an empty `AdCreativeVideoData` to create Creative videos.  

There is some workaround for this that i'm missing? 

The examples says that you must initialize `AdCreativeVideoData` using the default constructor, but it seems imposible with this new change.

**Comment by jingping2015** [comment]
https://github.com/facebook/facebook-java-business-sdk/blob/58312d246af94d40620c4d11af1d9ca83feeb887/src/main/java/com/facebook/ads/sdk/AdCreativeVideoData.java#L100
Hi, I think we have the public constructor in our latest release.

**Comment by lbadi** [comment]
Thanks 👍 i was using 3.2.0 !!
