### ISSUE TITLE
Geolocation targeting types are overall wrong

### ISSUE THREAD

**Issue by nicolasdalsass** [facebook/facebook-java-business-sdk#201]
In https://github.com/facebook/facebook-java-business-sdk/blob/master/src/main/java/com/facebook/ads/sdk/Targeting.java , there usually was two alternatives to provide a sub-targeting : through json strings, or using a specialized class.

For example (but all geoloc fields are affected !), mCities could be provided using TargetingGeoLocationCity.

Right now, this is no longer possible because :

- ~It became impossible to build instances of TargetingGeoLocationCity since the no arg constructor is no longer public. The only available constructor is fetch(), but this doesn't make sense since there's nowhere to fetch the information anyway.~ My bad, this has been fixed in the very latest release

- The setter in Targeting expects instances of IdName. But this is incorrect considering the api specification and it should in fact expect TargetingGeoLocationCity

The situation is the same for TargetingGeoLocationCustomLocation, TargetingGeoLocationElectoralDistrict, TargetingGeoLocationRegion, TargetingGeoLocationZip and TargetingGeoLocationMarket

**Comment by jingping2015** [comment]
Thanks for reporting the issue. Could you provide the permalink of the setter function ?

**Comment by nicolasdalsass** [comment]
For cities (e.g) : https://github.com/facebook/facebook-java-business-sdk/blob/58312d246af94d40620c4d11af1d9ca83feeb887/src/main/java/com/facebook/ads/sdk/Targeting.java#L469

**Comment by nicolasdalsass** [comment]
I just noticed that the setters for those fields with the correct signatures have been readded in v3.2.1 in the `TargetingGeoLocation` class, making it possible to use types again :+1: 

Which means setters in Targeting could be dropped instead of fixed if you should choose so.

**Comment by jingping2015** [comment]
Thanks! I am going to close this bug since it is not blocking you right now.
