### ISSUE TITLE
In targeting, included custom audiences and excludes ones aren't set with the same type

### ISSUE THREAD

**Issue by nicolasdalsass** [facebook/facebook-java-business-sdk#202]
Hi,

In targeting, the method setFieldCustomAudiences https://github.com/facebook/facebook-java-business-sdk/blob/58312d246af94d40620c4d11af1d9ca83feeb887/src/main/java/com/facebook/ads/sdk/Targeting.java#L547 and setFieldExcludedCustomAudiences https://github.com/facebook/facebook-java-business-sdk/blob/58312d246af94d40620c4d11af1d9ca83feeb887/src/main/java/com/facebook/ads/sdk/Targeting.java#L730 don't use the same parameter types.

Those two classes are somewhat compatible, since they have the same fields, but it feels a bit weird to use.

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is because they have different type defined in Graph API, if this block you, Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!

**Comment by nicolasdalsass** [comment]
Hi !

From an outsider perspective, they're very much identical in the doc :  https://developers.facebook.com/docs/marketing-api/targeting-specs/ so I'll let you handle internal typing at facebook if you want ^^

It's not blocking for me, just a QOL remark since it's a bit annoying having two types for essentially the same thing !

Thanks for your answer :-)
