### ISSUE TITLE
Campaign.fetchById is requesting deprecated fields

### ISSUE THREAD

**Issue by salunkeganesh93** [facebook/facebook-java-business-sdk#204]
Similar to https://github.com/facebook/facebook-java-business-sdk/issues/198

As mentioned in graph api version 3.0 changelog
https://developers.facebook.com/docs/graph-api/changelog/version3.0#gapi-change
`kpi_type, kpi_custom_conversion_id` fields were deprecated in v3.0
refer (https://github.com/facebook/facebook-java-business-sdk/commit/2fb8b65b6b61c85d90be79e0453727730d83fb63#r31370991)

These fields were added back in 3.2.0
refer (https://github.com/facebook/facebook-java-business-sdk/commit/108584ff583f981da5dead8f5925b5f6cbfad922#r31370901)

Now the `Campaign.fetchById` call is broken. Its failing with following error
`{
  "error": {
    "message": "(#12) kpi_type field is deprecated for versions v3.0 and higher",
    "type": "OAuthException",
    "code": 12,
    "fbtrace_id": "C/f0Gt8Bjps"
  }
}`

note : 
This call works with sdk v3.1

**Comment by jingping2015** [comment]
This has been solved in recent release.
