### ISSUE TITLE
Ad.fetchByID() is requesting deprecated field

### ISSUE THREAD

**Issue by Benoit-Bo** [facebook/facebook-java-business-sdk#205]
Hello,

As mentioned in others issues, since 3.0 the methods "fetchByID()" or "requestAllFields()" are calling deprecated fields, even though it was supposed to [be fixed in the next release](https://github.com/facebook/facebook-java-business-sdk/issues/198#issuecomment-436723232) (3.2.2) 
Today, I've seen another one on "Ad.fetchByID()" : 
`{"error":{"message":"(#12) objective_source field is deprecated for versions v3.2 and higher","type":"OAuthException","code":12,"fbtrace_id":"G5MFZn\/nSic"}}`

Since this one is deprecated for versions 3.2 I suppose it's new ?

**Comment by jingping2015** [comment]
This should already be fixed in our recent release. (3.2.3)
