### ISSUE TITLE
Release 3.2.3 whitelist error when retrieving adset

### ISSUE THREAD

**Issue by joeEulerity** [facebook/facebook-java-business-sdk#209]
I was able to work around this by commenting out the following fields in AdSet.java

ad_keywords
full_funnel_exploration_mode

To help those searching for the issue, the following was the response from the server

com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#10) The ad account and app id must be whitelisted","type":"OAuthException","code":10,"fbtrace_id":"xxxxxx"}

**Comment by jingping2015** [comment]
Hi, Some fields may need some special permission to access.  I would suggest you to specific the fields you want in the API call, something like : 
```
      new AdSet.APIRequestGet(id, context)
          .requestFields(...)
          .execute();
```

**Comment by Balineni** [comment]
It fails because of the field "best_creative" for me.

**Comment by Nahid1012** [comment]
Whitelist failed
