### ISSUE TITLE
Set Promoted Object to Ad Set not typed.

### ISSUE THREAD

**Issue by lbadi** [facebook/facebook-java-business-sdk#210]
There is a chance to type the .setPromotedObject method of the `APIRequestCreateAdSet` ? If think that the way to use it right now is very error prone.

**Comment by jingping2015** [comment]
Hi, Thanks for the feedback. 
It will be great you can make a pull request or give us a example here.

**Comment by jingping2015** [comment]
We're a small team, and it doesn't look as though anyone in the community is actively working on this issue, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know in the comments and we will re-open it and assign it to you. If you feel this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
