### ISSUE TITLE
Invalid field when request all fields from campaign

### ISSUE THREAD

**Issue by lbadi** [facebook/facebook-java-business-sdk#215]
Exception when request all fields from a campaign. `com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#100) Tried accessing nonexisting field (metrics_metadata) on node type (AdCampaignGroup)","type":"OAuthException","code":100,"fbtrace_id":"EyWjikl0kKO"}}`

it seems that the metrics_metadata fields doesn't exist, at least is not present on the official documentation. (https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group/)

I will open a pr to fix this.

**Comment by jingping2015** [comment]
This should be fix in next release, thanks for your report!

**Comment by mawr92** [comment]
Hi @jingping2015,

I'm currently working on the upgrade of the Marketing API and I'm getting this same error as an exception when posting campaigns. Is this going to be solved before February 1st? (When version 3.0 is deprecated). 

Thank you!

**Comment by jingping2015** [comment]
@mawr92  we already have our new release there, it should fix this issue. I am going to close it and let me know if this still a issue.
