### ISSUE TITLE
APIRequestGetInsights doesn't have any FIELDS

### ISSUE THREAD

**Issue by lbadi** [facebook/facebook-java-business-sdk#218]
The `FIELDS` array of AdAccount.APIRequestGetInsights is empty. This should have all the possible fields of the insights api. (https://developers.facebook.com/docs/marketing-api/insights/parameters).

It could make a pr to solve this if you wanna. :)

**Comment by jrg091** [comment]
I've added a new issue that might be related. There are some new fields that is not clear if they should be also as well: https://github.com/facebook/facebook-java-business-sdk/issues/221
