### ISSUE TITLE
Deprecated API version error while trying to create custom audience using sdk

### ISSUE THREAD

**Issue by ddey2** [facebook/facebook-java-business-sdk#222]
### Which SDK version are you using?
3.0.0
### What's the issue?
I want to create a custom audience.
#### Observed Results:
I am using java version of com.facebook.business.sdk. I am currently getting an error saying:
com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v3.1.","type":"OAuthException","code":2635,"fbtrace_id":"H9e4dafiA2s"}

**Comment by jingping2015** [comment]
You need update your  SDK to newer version, SDK v3.0.0 call API v3.0 which is deprecated. You should call v3.1.x or v3.2.x version. 
Here are more context about our business API version deprecation. https://developers.facebook.com/docs/marketing-api/versions/
