### ISSUE TITLE
get error "Requires ads_management permission to manage the object" when app status is live,but status is in development not error. how can i solve that?

### ISSUE THREAD

**Issue by ramazanisik** [facebook/facebook-java-business-sdk#223]
#### Observed Results:

  * What happened?  This could be a description, log output, etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
