### ISSUE TITLE
Please provide correct typing for LeadgenForm's tracking_parameters field

### ISSUE THREAD

**Issue by gdelprete** [facebook/facebook-java-business-sdk#224]
### Which SDK version are you using?
3.2.6
### What's the issue?
LeadgenForm's tracking_parameters field is not appropriately typed.
### Steps/Sample code to reproduce the issue
Get a LeadgenForm while requesting all fields.
#### Observed Results:

  * What happened?  This could be a description, log output, etc.

#### Expected Results:

  * What did you expect to happen?
tracking_parameters should be a Map<String, String> or at least a List of some Pair-type.

**Comment by gdelprete** [comment]
LeadGenDataDraft too has the same problem.

**Comment by hbrittner** [comment]
It looks like the change was made to Map<String, String>, but this also doesn't work.
Locally I made a KeyValuePair object, String key and String value. Replacing the type of tracking_parameters with this seems to work in my test.

I'm unsure if anything else will break if this change is made overall, but at least the parsing would work consistently.
