### ISSUE TITLE
fetchById method in CustomAudience class is giving error

### ISSUE THREAD

**Issue by ddey2** [facebook/facebook-java-business-sdk#226]
### Which SDK version are you using?
v3.2.0
### What's the issue?
I am using java sdk to fetch and update custom audience. i'm getting the following error for custom audience 23843389301200747

{"error":{"message":"(#100) Policy ID is not available for Ad Account.","type":"OAuthException","code":100,"fbtrace_id":"FvgtflWZfXB"}}

The ad account used here is 1922498521332608.

**Comment by ddey2** [comment]
Could somebody please advise on this?

I tried explicitly specifying the fields. The custom audience I am getting after specifying the fields, I can no longer update new user id to that custom audience.

**Comment by ddey2** [comment]
@jingping2015 Hi Jing, you helped me earlier. Can you please take a look at this issue? I haven't got any response on this.

**Comment by jingping2015** [comment]
Hi, we will try to fix this ASAP. At the meantime, you can adjust your call like this 
```
    CustomAudience custom_audience = new CustomAudience.APIRequestGet(custom_audienceID, context).requestFields(Arrays.asList(
              'account_id',
              ... // all fields you needed
          )).execute();
```
rather than call `fetchById `
