### ISSUE TITLE
Using withAutoPaginationIterator(true) ignores setParam("limit", value)

### ISSUE THREAD

**Issue by mosheeshel** [facebook/facebook-java-business-sdk#230]
### Which SDK version are you using?
Using Java SDK 3.2.9
### What's the issue?
Want to use the AutoPagination feature, but 25 items per page seems like to little, tried to set the limit in the original query, but it seems to be ignored when using the AutoPaginationIterator feature.
How can increase the number of elements returned with each nextPage()?

### Steps/Sample code to reproduce the issue
```
AdAccount.APIRequestGetInsightsAsync insights = adAccount.getInsightsAsync().requestFields(fields_names)
                    .setLevel(AdsInsights.EnumLevel.VALUE_ADSET)
                    .setTimeIncrement("1")
//                    .setDatePreset(datePreset)
                    .setTimeRange(dateRange)
                    .setBreakdowns(Arrays.asList(AdsInsights.EnumBreakdowns.VALUE_PRODUCT_ID))
                    .setActionBreakdowns(Arrays.asList(AdsInsights.EnumActionBreakdowns.VALUE_ACTION_TYPE))
                    .setActionAttributionWindows(Arrays.asList(AdsInsights.EnumActionAttributionWindows.VALUE_1D_CLICK, AdsInsights.EnumActionAttributionWindows.VALUE_1D_VIEW))
                    .setFiltering("[{'field':'ad.effective_status','operator':'IN','value':['ACTIVE']},{'field':'impressions','operator':'GREATER_THAN','value':0}]")
                    .setParam("limit", 1000);

AdReportRun reportRun = insights.execute().fetch(); 

            boolean jobComplete = false;
            AdReportRun reportRun = insights.execute().fetch();
            while (!jobComplete) {
                try {
                    AdReportRun adReportRun = reportRun.fetch();
                    jobComplete = (adReportRun.getFieldAsyncPercentCompletion() == 100 && "Job Completed".equals(adReportRun.getFieldAsyncStatus()));
                    LOGGER.info("Job progressing: {}%, Job Status: {}", adReportRun.getFieldAsyncPercentCompletion(), adReportRun.getFieldAsyncStatus());
                    Thread.sleep(3000);
                } catch (InterruptedException e) {
                    LOGGER.error("Thread interuppted from sleep while waiting for async insights");
                }
            }

            APINodeList<AdsInsights> adsInsights = reportRun.getInsights().execute().withAutoPaginationIterator(true);
```

#### Observed Results:

Sample page request (`enableDebug(true)`)
========Start of API Call========
Request:
GET: https://graph.facebook.com/v3.2/7777777/insights?access_token=...qMT2A&limit=25&after=MzE0NDkZD&appsecret_proof=d0cf249756....
Response:
{"data":[{"adset_id":"999","campaign_id":"888","date_start":"2018-11-01","clicks":"0","inline_link_clicks":"0","cpm":"10","ctr":"0","impressions":"3","spend":"0.03","date_stop":"2018-11-01","product_id":"666, product","account_id":"7777777"},
....
],"paging":{"cursors":{"before":"MzE0NTAZD","after":"MzE0NzQZD"},"next":"https:\/\/graph.facebook.com\/v3.2\/7777777\/insights?access_token=EAAAAIm3moD0BA...&limit=25&after=MzE0NzQZD","previous":"https:\/\/graph.facebook.com\/v3.2\/7777777\/insights?access_token=EAAAAIm3moD0....&limit=**25**&before=MzE0NTAZD"}}
========End of API Call========

#### Expected Results:

  * What did you expect to happen?
========Start of API Call========
Request:
GET: https://graph.facebook.com/v3.2/7777777/insights?access_token=...qMT2A&limit=25&after=MzE0NDkZD&appsecret_proof=d0cf249756....
Response:
{"data":[{"adset_id":"999","campaign_id":"888","date_start":"2018-11-01","clicks":"0","inline_link_clicks":"0","cpm":"10","ctr":"0","impressions":"3","spend":"0.03","date_stop":"2018-11-01","product_id":"666, product","account_id":"7777777"},
....
],"paging":{"cursors":{"before":"MzE0NTAZD","after":"MzE0NzQZD"},"next":"https:\/\/graph.facebook.com\/v3.2\/7777777\/insights?access_token=EAAAAIm3moD0BA...&limit=25&after=MzE0NzQZD","previous":"https:\/\/graph.facebook.com\/v3.2\/7777777\/insights?access_token=EAAAAIm3moD0....&limit=**1000**&before=MzE0NTAZD"}}

**Comment by maxkremer** [comment]
is this still an issue?
