### ISSUE TITLE
SDK 3.2.10 returns "Object" instead of "Campaign", "AdSet", "Ad"

### ISSUE THREAD

**Issue by VictorNetflix** [facebook/facebook-java-business-sdk#232]
Just saw the new release 3.2.10 and it seems to have "regressed" in terms of function-return-types? For example, Ad.getFieldCampaign() now returns Object instead of Campaign? So now I can't call Campaign methods on the returned value?

https://github.com/facebook/facebook-java-business-sdk/commit/7e7b19a16e70a99a5b54de56672b8822628caf2e#diff-4f27ad7051d2fd267b53a64c1d204c54

Is that to be expected, or a bug in the auto-generated Java code?

**Comment by jingping2015** [comment]
Hi, Thanks for raise this issue. This should be fix in our recent release.
