### ISSUE TITLE
Object(Campaign,Adset,...) fields wrong

### ISSUE THREAD

**Issue by tiger154** [facebook/facebook-java-business-sdk#234]
### Which SDK version are you using?
v3.2.11
### What's the issue?

When use requestAllFields() function, error occure for Objects(Campaign,Adset,Ad,CustomAudience). 

I saw this kind of problem long time since 3.2+ update.

If we use requestAllFields() It should be return all fields written from official document only,
But it requesting not written fields as well. so it should be fixed. And many of them looks like 
testing fields there.

Or support some safe function such as 'requestAllFieldsSafe()' which only request fields written from official document. 

### Steps/Sample code to reproduce the issue

new Campaign("11111", new APIContext('xxxxx','xxxxx')).get().requestAllFields().execute();
new AdSet("11111", new APIContext('xxxxx','xxxxx')).get().requestAllFields().execute();
new Ad("11111", new APIContext('xxxxx','xxxxx')).get().requestAllFields().execute();
new CustomAudience("11111", new APIContext('xxxxx','xxxxx')).get().requestAllFields().execute();

#### Observed Results:

  * What happened?  This could be a description, log output, etc.

 There are many different errors but this is one of example when tried to get data of custom-audience with requestAllFields(); 

{
  "error": {
    "message": "(#100) Policy ID is not available for Ad Account.",
    "type": "OAuthException",
    "code": 100,
    "fbtrace_id": "An3SBsxjGb5"
  }
}

#### Expected Results:

  * What did you expect to happen?

If we use requestAllFields() It should be return all fields written from official document.
But it requesting not written fields. so it should be fixed. And many of them looks like 
testing fields there.

Or support some safe function such as 'requestAllFieldsSafe()' which only request fields written from official document. 

#### Additional information

I checked all four objects fields from official document and compared with SDK 3.2.11's fields.
I can see there are many fields not explained and don't know why its' in SDK. 

there are two type EXIST, NO EXIST. please make sure NO EXIST fields is removed from next release or support safe function.

1. Custom Audience

- Official Document: https://developers.facebook.com/docs/marketing-api/reference/custom-audience/v3.2#Reading
- SDK Git URL: https://github.com/facebook/facebook-java-business-sdk/blob/v3.2.11/src/main/java/com/facebook/ads/sdk/CustomAudience.java#L3682

 

	1) SDK 

	{"account_id" --> EXIST 
	"approximate_count"  --> EXIST 
	"customer_file_source"  --> EXIST 
	"data_source"  --> EXIST 
	"data_source_types" --> NO EXIST!!! 
	"datafile_custom_audience_uploading_status" --> NO EXIST!!!
	"delivery_status"--> EXIST 
	"description"--> EXIST 
	"excluded_custom_audiences"--> NO EXIST!!! 
	"expiry_time"--> NO EXIST!!! 
	"external_event_source"--> EXIST 
	"household_audience"--> NO EXIST!!! 
	"id"--> EXIST 
	"included_custom_audiences"--> NO EXIST!!!
	"is_household"--> NO EXIST!!!
	"is_snapshot"--> NO EXIST!!!
	"is_value_based"--> EXIST
	"list_of_accounts"--> EXIST
	"lookalike_audience_ids"--> EXIST
	"lookalike_spec"--> EXIST
	"name"--> EXIST
	"operation_status"--> EXIST
	"opt_out_link"--> EXIST
	"permission_for_actions"--> EXIST
	"pixel_id"--> EXIST
	"retention_days"--> EXIST
	"rev_share_policy_id"--> NO EXIST!!!
	"rule"--> EXIST
	"rule_aggregation"--> EXIST
	"rule_v2"--> NO EXIST!!!
	"seed_audience"--> NO EXIST!!!
	"sharing_status"--> EXIST
	"study_spec"--> NO EXIST!!!
	"subtype"--> EXIST
	"time_content_updated"--> EXIST
	"time_created"--> EXIST
	"time_updated"--> EXIST};

	 

	2) Document NON EXIST Fields

	"data_source_types" --> NO EXIST!!! 
	"datafile_custom_audience_uploading_status" --> NO EXIST!!!
	"excluded_custom_audiences"--> NO EXIST!!! 
	"expiry_time"--> NO EXIST!!! 
	"household_audience"--> NO EXIST!!! 
	"included_custom_audiences"--> NO EXIST!!!
	"is_household"--> NO EXIST!!!
	"is_snapshot"--> NO EXIST!!!
	"rev_share_policy_id"--> NO EXIST!!!
	"rule_v2"--> NO EXIST!!!
	"seed_audience"--> NO EXIST!!!
	"study_spec"--> NO EXIST!!!
 

2. Campaign 

- Official Document:  https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group/v3.2#Reading
- SDK Git URL: https://github.com/facebook/facebook-java-business-sdk/blob/v3.2.11/src/main/java/com/facebook/ads/sdk/Campaign.java#L3419

 

	1) SDK 

	{"account_id"--> EXIST
	"adlabels"--> EXIST
	"bid_strategy"--> EXIST
	"boosted_object_id"--> EXIST
	"brand_lift_studies"--> EXIST
	"budget_rebalance_flag"--> EXIST
	"budget_remaining"--> EXIST
	"buying_type"--> EXIST
	"can_create_brand_lift_study"--> EXIST
	"can_use_spend_cap"--> EXIST
	"configured_status"--> EXIST
	"created_time"--> EXIST
	"daily_budget"--> EXIST
	"effective_status"--> EXIST
	"id"--> EXIST
	"issues_info"--> EXIST
	"last_budget_toggling_time"--> NO EXIST!!!
	"lifetime_budget"--> EXIST
	"name"--> EXIST
	"objective"--> EXIST
	"pacing_type"--> NO EXIST!!!
	"promoted_object"--> EXIST
	"recommendations"--> EXIST
	"source_campaign"--> EXIST
	"source_campaign_id"--> EXIST
	"spend_cap"--> EXIST
	"start_time"--> EXIST
	"status"--> EXIST
	"stop_time"--> EXIST
	"topline_id"--> NO EXIST!!!
	"updated_time"--> EXIST};

	 

	2) Document None EXIST fields

	"last_budget_toggling_time"--> NO EXIST!!!
	"pacing_type"--> NO EXIST!!!
	"topline_id"--> NO EXIST!!!

 

3. AdSet

- Official Document:  https://developers.facebook.com/docs/marketing-api/reference/ad-campaign/v3.2#Reading
- SDK Git URL: https://github.com/facebook/facebook-java-business-sdk/blob/v3.2.11/src/main/java/com/facebook/ads/sdk/AdSet.java#L4764

 

	1) SDK 

	"account_id"--> EXIST
	"ad_keywords"--> NO EXIST!!!
	"adlabels"--> EXIST
	"adset_schedule"--> EXIST
	"asset_feed_id"--> NO EXIST!!!
	"attribution_spec"--> EXIST
	"best_creative"--> NO EXIST!!!
	"bid_adjustments"--> NO EXIST!!!
	"bid_amount"--> EXIST
	"bid_constraints"--> NO EXIST!!!
	"bid_info"--> EXIST
	"bid_strategy"--> EXIST
	"billing_event"--> EXIST
	"budget_remaining"--> EXIST
	"campaign"--> EXIST
	"campaign_id"--> EXIST
	"configured_status"--> EXIST
	"created_time"--> EXIST
	"creative_sequence"--> EXIST
	"daily_budget"--> EXIST
	"daily_min_spend_target"--> EXIST
	"daily_spend_cap"--> EXIST
	"destination_type"--> EXIST
	"effective_status"--> EXIST
	"end_time"--> EXIST
	"frequency_control_specs"--> EXIST
	"full_funnel_exploration_mode"--> NO EXIST!!!
	"id"--> EXIST
	"instagram_actor_id"--> EXIST
	"is_dynamic_creative"--> EXIST
	"issues_info"--> EXIST
	"lifetime_budget"--> EXIST
	"lifetime_imps"--> EXIST
	"lifetime_min_spend_target"--> EXIST
	"lifetime_spend_cap"--> EXIST
	"name"--> EXIST
	"optimization_goal"--> EXIST
	"pacing_type"--> EXIST
	"promoted_object"--> EXIST
	"recommendations"--> EXIST
	"recurring_budget_semantics"--> EXIST
	"review_feedback"--> NO EXIST!!!
	"rf_prediction_id"--> EXIST
	"source_adset"--> EXIST
	"source_adset_id"--> EXIST
	"start_time"--> EXIST
	"status"--> EXIST
	"targeting"--> EXIST
	"time_based_ad_rotation_id_blocks"--> EXIST
	"time_based_ad_rotation_intervals"--> EXIST
	"updated_time"--> EXIST
	"use_new_app_click"--> EXIST

	 

	2) Document None EXIST Fields

	"ad_keywords"--> NO EXIST!!!
	"asset_feed_id"--> NO EXIST!!!
	"best_creative"--> NO EXIST!!!
	"bid_adjustments"--> NO EXIST!!!
	"bid_constraints"--> NO EXIST!!!
	"full_funnel_exploration_mode"--> NO EXIST!!!
	"review_feedback"--> NO EXIST!!!

 

 

4. Ad 
 

- Official Document:  https://developers.facebook.com/docs/marketing-api/reference/adgroup/v3.2#Reading
- SDK fields: https://github.com/facebook/facebook-java-business-sdk/blob/15a5b6b1b51f68594c5913d9afa2fbf6cc9610d2/src/main/java/com/facebook/ads/sdk/Ad.java#L3971

 

 

"account_id"--> EXIST
"ad_review_feedback"--> EXIST
"adlabels"--> EXIST
"adset"--> EXIST
"adset_id"--> EXIST
"bid_amount"--> EXIST
"bid_info"--> EXIST
"bid_type"--> EXIST
"campaign"--> EXIST
"campaign_id"--> EXIST
"configured_status"--> EXIST
"conversion_specs"--> EXIST
"created_time"--> EXIST
"creative"--> EXIST
"demolink_hash"--> NO EXIST!!!
"display_sequence"--> EXIST
"effective_status"--> EXIST
"engagement_audience"--> NO EXIST!!!
"failed_delivery_checks"--> NO EXIST!!!
"id"--> EXIST
"issues_info"--> EXIST
"last_updated_by_app_id"--> EXIST
"name"--> EXIST
"priority"--> NO EXIST!!!
"recommendations"--> EXIST
"source_ad"--> EXIST
"source_ad_id"--> EXIST
"status"--> EXIST
"targeting"--> NO EXIST!!!
"tracking_and_conversion_with_defaults"--> NO EXIST!!!
"tracking_specs"--> EXIST
"updated_time"--> EXIST

 

2) Document None EXIST Fields

"demolink_hash"--> NO EXIST!!!
"engagement_audience"--> NO EXIST!!!
"failed_delivery_checks"--> NO EXIST!!!
"priority"--> NO EXIST!!!
"targeting"--> NO EXIST!!!
"tracking_and_conversion_with_defaults"--> NO EXIST!!!

**Comment by jingping2015** [comment]
Hi, Thanks for raise this issue. We will working on this soon. In the meantime, you can remove these not worked fields.
For example 
``` java
CustomAudience ca = new CustomAudience(ID, context).get().requestAllFields().requestRevSharePolicyIdField(false)....execute();
```

Or you can only specific the fields you want to fetch :
```java
AdAccount adaccount = new AdAccount.APIRequestGet(adaccount_id,context).requestFields(Arrays.asList(
    "id",
    "name"
)).execute();
```
