### ISSUE TITLE
weird Enum pattern causes problems for clients

### ISSUE THREAD

**Issue by andersonbd1** [facebook/facebook-java-business-sdk#235]
Wouldn't it make more sense for your Enum constants to look like this:

```
  public static enum EnumCustomerFileSource {
      BOTH_USER_AND_PARTNER_PROVIDED,
      PARTNER_PROVIDED_ONLY,
      ...
      // NULL isn't necessary
  }
```

as opposed to this:

```
  public static enum EnumCustomerFileSource {
      @SerializedName("BOTH_USER_AND_PARTNER_PROVIDED")
      VALUE_BOTH_USER_AND_PARTNER_PROVIDED("BOTH_USER_AND_PARTNER_PROVIDED"),
      @SerializedName("PARTNER_PROVIDED_ONLY")
      ...
      NULL(null);

      private String value;

      private EnumCustomerFileSource(String value) {
        this.value = value;
      }

      @Override
      public String toString() {
        return value;
      }
  }
```
it's less code, simpler, and avoids problems like this for clients:
https://github.com/FasterXML/jackson-databind/issues/2309

**Comment by andersonbd1** [comment]
@jingping2015 - any thoughts on this?

**Comment by jingping2015** [comment]
Hi ,
Thanks for reporting this issue. Actually `@SerializedName` annotation is used for serializing and deserializing by GSON.  So we are not be able to just have enum constants like you proposed.

**Comment by andersonbd1** [comment]
Thanks @jingping2015 .  What about the `NULL(null);`.  Is that really necessary?  It doesn't work with Jackson (see link above).
