### ISSUE TITLE
LeadgenForm.fetchById() - Unsupported get request

### ISSUE THREAD

**Issue by SubtypeZero** [facebook/facebook-java-business-sdk#238]
### Which SDK version are you using?
v3.3

### What's the issue?
Unable to fetch leadgen form by ID

### Steps/Sample code to reproduce the issue
LeadgenForm.fetchById(form_id, context);

#### Observed Results:
Seems to always throw a FailedRequestException

When using version 3.2 of the API, everything appears to work as expected. Switching to 3.3 seems to be the issue.

#### Expected Results:
Return data for a leadgen form

**Comment by gdelprete** [comment]
Dunno if it helps, but for me, using version 3.3.3, this works:

final LeadgenForm form = new LeadgenForm("<id>", apiContext).get()
                                                                               .requestAllFields()
                                                                               .execute();

**Comment by jingping2015** [comment]
Could you provide more information about the failure ?
Does it works if you make a raw API request call ?
