### ISSUE TITLE
Errors with Java source code?

### ISSUE THREAD

**Issue by spaldingl** [facebook/facebook-java-business-sdk#242]
### Which SDK version are you using?
3.0.0

### What's the issue?
When I download the SDK it has multiple errors across all files

### Steps/Sample code to reproduce the issue
Download the facebook-java-business-sdk folder, open in Eclipse as a new project

#### Observed Results:
Every file in src/main/java/com/facebook/ads/sdk has this error in it: "The return type is incompatible with APINode.parseResponse(String, APIContext, APIRequest<APINode>, String)"

Most of the files in the examples folder give this error: "The method setFieldId(String) in the type IDName is not applicable for the arguments (long)"

#### Expected Results:
I expected to be able to run the files in the examples folder without having to fix hundreds of errors. Did I miss something in the setup of the SDK or does it just come with errors in it?

**Comment by jingping2015** [comment]
For the examples, we din't fill any real ID, we fill something like `<adCreativeID>`, you can just replace with your own ID to run this code. They are just examples, not expected to be able to run directly.

**Comment by spaldingl** [comment]
Yes I know that you need to fill in your own ID, token etc. But there are issues with your code. Try downloading the SDK and calling a`ccount.getInsights().setBreakdowns(Arrays.asList());` and you'll see what I mean. Also there should be some sort of documentation describing how you can't actually call conversions, among others, as a field, you have to call actions. This makes no sense and is not mentioned anywhere.

**Comment by spaldingl** [comment]
It's also no help to come here a month after a question was asked, beat around the bush in the answer, then close the thread. Who does that help?

**Comment by perezdf** [comment]
Do you know if there is a more stable fork or development Community in order to work based on that?

**Comment by sandalo-bee** [comment]
Hi guys, Is there no solution for this compilation problem?
