### ISSUE TITLE
NullPointerException while retirieving AdAccounts. This issue only occurs when the code is run in our cloud desktop and not in our local desktop.

### ISSUE THREAD

**Issue by kiran-suresh** [facebook/facebook-java-business-sdk#243]
### Which SDK version are you using?
Facebook Java Business SDK
### What's the issue?
This error does not occur for us when we run it in our local computer. But when we deploy it in our cloud we are getting this error. We have made sure that our API call is going right and also that the business ID we are using to retrieve this information is correct. We also did not have any error while running this on the Graph API.
We think this github issue that was closed without any solution from the Facebook team might be similar to ours - https://github.com/facebook/facebook-java-business-sdk/issues/208

![Screen Shot 2019-06-20 at 10 37 27 AM](https://user-images.githubusercontent.com/26031489/59958929-1b2b3380-9463-11e9-90fc-e18e8419893f.png)

**Comment by kevinwenzhang** [comment]
We have this exact same issue. We've deployed a Spring Boot application in Google Cloud and we keep getting these NPEs whenever the application starts up. It runs without any issues locally, and I've confirmed the exact same requests return results in the Graph Explorer.

@kiran-suresh, did you ever resolve this issue?
