### ISSUE TITLE
Getting back Null Values while requesting email id's for a given user even with all right permissions

### ISSUE THREAD

**Issue by kiran-suresh** [facebook/facebook-java-business-sdk#244]
### Which SDK version are you using?
Facebook Java Business SDK
### What's the issue?
I am getting null values returned when requesting the email ids of users even with all the right permissions. 
### Steps/Sample code to reproduce the issue
I pass the user's id to the APIRequestGet class in the BusinessUser.Java file and use the requestEmailField method to get the email ids but I am getting null values. It seems as if only this method is not working as the method requestFirstNameField works just fine.

**Comment by jingping2015** [comment]
Do you get back email if you make same raw API call ?
