### ISSUE TITLE
Conversions Won't Print Out With Other Fields

### ISSUE THREAD

**Issue by spaldingl** [facebook/facebook-java-business-sdk#245]
Which SDK version are you using?
3.0.0

What's the issue?
I'm trying to print out clicks, spend, and conversions, but conversions won't print

Steps/Sample code to reproduce the issue:

```
import com.facebook.ads.sdk.*;
import com.facebook.ads.sdk.AdAccount.APIRequestGetInsights;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

public class FBReportGen {
  public static void main(String[] args) throws APIException, IOException {

    String access_token = "xxx";
    String ad_account_id = "xxx";
    String app_secret = "xxx";
    String app_id = "xxx";
    APIContext context = new APIContext(access_token, app_secret).enableDebug(true);

      AdAccount account = new AdAccount(ad_account_id, context);
      String yeet = account.getInsights()
      .setLevel(AdsInsights.EnumLevel.VALUE_ACCOUNT)
      .setFiltering("[]")
      .setBreakdowns(Arrays.asList())
      .setTimeRange("{\"since\":\"2019-07-14\",\"until\":\"2019-07-14\"}")
      .requestField("clicks")
      .requestField("spend")
      .requestField("conversions")
      .execute();
      
  }
}
```
Observed Results:

{
   "data": [
      {
         "clicks": "240",
         "spend": "203.6",
         "date_start": "2019-07-14",
         "date_stop": "2019-07-14"
      }
   ],
   "paging": {
      "cursors": {
         "before": "MAZDZD",
         "after": "MAZDZD"
      }
   }
}

Expected Results:
{
   "data": [
      {
         "clicks": "240",
         "spend": "203.6",
         **"conversions": "12",**
         "date_start": "2019-07-14",
         "date_stop": "2019-07-14"
      }
   ],
   "paging": {
      "cursors": {
         "before": "MAZDZD",
         "after": "MAZDZD"
      }
   }
}

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!

**Comment by xieqiang9527** [comment]
> 

Has this problem been fixed? I still can't see conversions and purchase_ ROAs and other fields, thank you very much
