### ISSUE TITLE
enable_fetch_or_create not working

### ISSUE THREAD

**Issue by krozum** [facebook/facebook-java-business-sdk#246]
### Which SDK version are you using?
3.3.3
### What's the issue?
I'm trying create custom audience, but even if i have enable_fetch_or_create = true, i got error that custom audience exist.

### Steps/Sample code to reproduce the issue
`             CustomAudience customAudience = new AdAccount(AD_ACCOUNT_ID, context).createCustomAudience()
                    .setName(name)
                    .setEnableFetchOrCreate(true)
                    .setSubtype(CustomAudience.EnumSubtype.VALUE_LOOKALIKE)
                    .setLookalikeSpec("{ \"ratio\": 0.06, \"country\": \"" + COUNTRY + "\", \"page_id\": \"" + PAGE_ID + "\", \"conversion_type\": \"page_like\" }")
                    .execute();`

#### Observed Results:

`! Causing: com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#2654) Nie mo\u017cna utworzy\u0107 duplikatu grupy podobnych odbiorc\u00f3w: Utworzono ju\u017c grup\u0119 podobnych odbiorc\u00f3w o tym samym \u017ar\u00f3dle, kraju i wielko\u015bci. Spr\u00f3buj u\u017cy\u0107 innego \u017ar\u00f3d\u0142a lub innych specyfikacji.","type":"OAuthException","code":2654,"error_subcode":1713007,"fbtrace_id":"AqOgvEdDnPXnNFLZ_h98t_j"}}`

#### Expected Results:

API should return object of existing Custom Audience

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
