### ISSUE TITLE
Copying a campaign returns an empty campaign object

### ISSUE THREAD

**Issue by simonknoll** [facebook/facebook-java-business-sdk#247]
#### Maven repo
https://repo1.maven.org/maven2/com/facebook/business/sdk/facebook-java-business-sdk/3.3.3/
#### gradle
`compile 'com.facebook.business.sdk:facebook-java-business-sdk:3.3.3'`
### What's the issue?
When copying a campaign it copies the campaign, but it returns an empty result.
So accessing the id of the newly created campaign results in a nullpointer exception.

This is most probably because within the sdk it is tried to parse a copy response like a create response, but according to the API documentation theses responses are different.

### Steps/Sample code to reproduce the issue
```java
Campaign campaign = Campaign.fetchById(campaign_id, Configuration.CONTEXT);
Campaign copiedCampaign = campaign.createCopy().execute();
System.out.println(copiedCampaign.getId());
```
#### Observed Results:
  * Empty campaign object
  * Nullpointer exception is thrown

#### Expected Results:
  * Having campaign object, where e.g. the new campaign id is accessible
  * Printing out the id

**Comment by jingping2015** [comment]
Thanks for reporting this issue. 
https://github.com/facebook/facebook-java-business-sdk/commit/3135237d5973a3cff6148253a7b6948ed449ead9 Should fix this issue, please update your SDK version.
