### ISSUE TITLE
All values in AdsInsights.EnumBreakdowns are not present

### ISSUE THREAD

**Issue by abhishek9** [facebook/facebook-java-business-sdk#248]
### Which SDK version are you using?
4.0.0

### What's the issue?
AdsInsights.EnumBreakdowns.VALUE_DAYS_1 not available in SDK. But when we download sample code from facebook App panel, then it provides this Enum value in code.

#### Expected Results:

All EnumBreakdowns available in App panel should be available in SDK

**Comment by jingping2015** [comment]
Hi, Thanks for reporting the issue, can you please provide where you found the sample code from facebook App panel ?
