### ISSUE TITLE
AdSet.EnumEffectiveStatus values were removed from SDK but still in use in API

### ISSUE THREAD

**Issue by dev-om** [facebook/facebook-java-business-sdk#249]
### Which SDK version are you using?
3.3.3

### What's the issue?
Multiple AdSet.EnumEffectiveStatus values were removed from the SDK version in the upgrade from 3.3.1 to 3.3.2. Here's the commit: 

https://github.com/facebook/facebook-java-business-sdk/commit/6ac2b2a4399a49ffc5232a38344b3a3559d5ee27#diff-d9cf50ef1e0f8db4603af8c8faddca76

Differential Revision: D15422916
fbshipit-source-id: 0ae1744d

I think this was done by mistake. The API still returns these values (e.g. CAMPAIGN_PAUSED), but they cannot be mapped to the SDK enum, so we're getting no value at all there.

### Steps/Sample code to reproduce the issue

Have a paused campaign and an active adset inside.

AdAccount adAccount = new AdAccount(accountId, ApiContext);
AdAccount.APIRequestGetAdSets apiRequestGetAds = adAccount.getAdSets();
apiRequestGetAdSets.requestField("effective_status");
APINodeList<AdSet> response = apiRequestGetAdSets.execute();

#### Observed Results:

![image](https://user-images.githubusercontent.com/53787896/62476546-83ca3780-b7a7-11e9-92c4-0f26ac73299f.png)
no effective_status contained for the 2 adsets in the middle, because the API returns the value "campaign_paused" and that's not in the SDK anymore.

#### Expected Results:

![image](https://user-images.githubusercontent.com/53787896/62476608-a4928d00-b7a7-11e9-9e95-3e7fbf657278.png)

(This is the response using SDK v.3.3.1)

I'd appreciate if you could check this issue. I think the old effective status values should be restored in the SDK, because they are actually important and in use.

Thanks and best regards

**Comment by jingping2015** [comment]
Hi, if you check our external doc https://developers.facebook.com/docs/marketing-api/reference/ad-campaign/, you will found `campaign_paused ` is not a valid enum for `effective_status`.

**Comment by dev-om** [comment]
@jingping2015 well you can see that the FB Graph API returns this value. so the question would be: why is this value used by the API if you (and the documentation) consider it as "invalid".
Apparently, the SDK doesn't reflect what's used in the API (see screenshots above), and that causes problems on our side.
