### ISSUE TITLE
Update to the latest version: v4.0 - Not Possible

### ISSUE THREAD

**Issue by arnoe** [facebook/facebook-java-business-sdk#252]
### Which SDK version are you using?
3.3.3

Gradle: `compile "com.facebook.business.sdk:facebook-java-business-sdk:3.3.3"`

### What's the issue?

**Facebook API Response**

> You are calling a deprecated version of the Ads API. Please update to the latest version: v4.0.

I had a look at the Central Repository, not seeing any versions after 3.3.3
https://repo1.maven.org/maven2/com/facebook/business/sdk/facebook-java-business-sdk/

PS. This issue is related to #251 

![image](https://user-images.githubusercontent.com/866771/62860259-e66b8800-bcff-11e9-8228-22413895a800.png)

**Comment by arnoe** [comment]
Just checking in again,  is there any estimation on the maven distribution?

**Comment by wejaikao** [comment]
You can use another APIContext constructor:
APIContext(String endpointBase, String videoEndpointBase, String version, String accessToken, String appSecret)
to force the version.

**Comment by MasterDDT** [comment]
> You can use another APIContext constructor:
> APIContext(String endpointBase, String videoEndpointBase, String version, String accessToken, String appSecret)
> to force the version.

But if there are new required fields, this wont work right? We used to pass the string version, but things broke frequently, so now we just update the whole SDK version and recompile. It seems safer that way, right?

**Comment by jingping2015** [comment]
Thank you all for reporting this issue. Now we have 4.0.2 available.
