### ISSUE TITLE
What user fields can be hashed when update custom audience

### ISSUE THREAD

**Issue by darrenfu** [facebook/facebook-java-business-sdk#253]
### Which SDK version are you using?
Java SDK 4.0

### What's the issue?
Need detailed document which attributes can be sha256-ed.
Checked `payload` object in the [doc](https://developers.facebook.com/docs/marketing-api/reference/custom-audience/users/#Updating), it only mentions two fields: `EMAIL_SHA256` and `PHONE_SHA256`. What about first name, last name, etc? Per our company policy, those are all PII data, which requires hashing before uploading to facebook.
I also checked the Java SDK source code, didn't find any sha256 related fields besides these two fields. 
Can you confirm only two sha256 fields are supported so far?

**Comment by jingping2015** [comment]
Hi, Thanks for reporting this issue.
Actually you can hashed any fields , more context you can read this [doc](https://developers.facebook.com/docs/marketing-api/audiences-api/).

Yes, in java-sdk, we don't have any Multi-key field. But you can define `payload` by yourself.
