### ISSUE TITLE
how can i get access token in application program

### ISSUE THREAD

**Issue by SM10855** [facebook/facebook-java-business-sdk#256]
### Which SDK version are you using?
3.3.3

### What's the issue?

can i make refresh token with valid access token using API?
is there any solution refresh access token in java application?
Can access tokens be issued only on this site "https://developers.facebook.com/tools/explorer/"
without login flow?

### Steps/Sample code to reproduce the issue
 public static final APIContext context = new APIContext(ACCESS_TOKEN, APP_SECRET);

#### Observed Results:
when access token is invalid or expired then it 'll be refreshed about  client. not refresh the application auto.

**Comment by jingping2015** [comment]
Hi, Thanks for reposting the issue.
You should be able to find out more about how to get access token here https://developers.facebook.com/docs/facebook-login/access-tokens/

**Comment by SM10855** [comment]
I know that is. but should i get access token by only facebook login. can't get access token other way? like using only API call.
