### ISSUE TITLE
Does the facebook-java-business-sdk library use graphing api or use marketing api 

### ISSUE THREAD

**Issue by SM10855** [facebook/facebook-java-business-sdk#260]
### What's the issue?

Does the facebook-java-business-sdk library use graphing api or use marketing api when it requests accounts or getInsights? 
Marketing api version 3.3 will be available until January 13, 2020. I wonder if this library uses marketing api or graph api.
Which api version should I follow?

**Comment by jingping2015** [comment]
Should follow the marketing API version. Thanks!

**Comment by SM10855** [comment]
thank you :)
