### ISSUE TITLE
Marketing API Rate Limiting API 5.0

### ISSUE THREAD

**Issue by SM10855** [facebook/facebook-java-business-sdk#269]
### Which SDK version are you using?
5.0
### What's the issue?
API rate limit
#### Observed Results:

  * What happened?  This could be a description, log output, etc.

1)
What is different from between total_time and total_ cpu_time in X-Business-Use-Case Header?

2)
when I using facebook-java-business-sdk 5.0, total_time value is higher than total_time value. did it categorized by account?

3)
How can I lower that time value?. just should I wait next api call ? How  many minutes?
Could I expect that increasing call api ratio?

4)
`AdAccount account = new AdAccount(ACCOUNT_ID, context);
APINodeList<Campaign> campaigns = account.getCampaigns().requestAllFields().execute();
for(Campaign campaign : campaigns) {
	System.out.println(campaign.getFieldName());
}`

when i using this code,  which one is applied rate limit?
Platform Rate Limits
Applications
Calls within one hour = 200 * Number of Users

Business Use Case Rate Limits
Ads Insights
Calls within one hour = 190000 + 400 * Number of Active ads - 0.001 * User Errors

Pages
Calls within one hour = 4800 * Number of Engaged Users

thanks for reading.
#### Expected Results:

  * What did you expect to happen?

**Comment by Nathaaaalie** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
