### ISSUE TITLE
APIException: Tried accessing nonexisting field (is_autobid) on node type (Ad)

### ISSUE THREAD

**Issue by vegardoj** [facebook/facebook-java-business-sdk#270]
### Which SDK version are you using?

5.0.4

### What's the issue?

Fetching an Ad causes _(#100) Tried accessing nonexisting field (is_autobid) on node type (Ad)_
Field was deprecated for Ad in 3.0 and is still trying to be fetched when calling fetch on Ad in 5.0, causing APIException.

**Comment by macmillan78** [comment]
Seriously? Nobody responsible?

**Comment by guillermo-12gigs** [comment]
Using v6.0.3 and is broken for me too. Please fix

**Comment by macmillan78** [comment]
> Using v6.0.3 and is broken for me too. Please fix

I fixed it myself.

**Comment by guillermo-12gigs** [comment]
> > Using v6.0.3 and is broken for me too. Please fix
> 
> I fixed it myself.

Whaaaat? So you have to maintain your own version to carry this fix over?
