### ISSUE TITLE
Cannot call API on behalf of this user

### ISSUE THREAD

**Issue by lcy8765** [facebook/facebook-java-business-sdk#272]
### Which SDK version are you using?
 5.0.1
### What's the issue?
com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"Cannot call API on behalf of this user","type":"OAuthException","code":200,"fbtrace_id":"Alejv-8JFsErrF0_kplz11G"}}

### Steps/Sample code to reproduce the issue
when I use  VideoUtils.uploadVideoFileInChunks  to upload video, it returns   {"error":{"message":"Cannot call API on behalf of this user","type":"OAuthException","code":200,"fbtrace_id":"Alejv-8JFsErrF0_kplz11G"}}

But I was able to use it some time ago，I don't know what happened。Has anyone encountered a similar problem? and how to solve? I'm in a hurry。

**Comment by guyue001** [comment]
hi，I have the same problem, did you solve it?

**Comment by sathieshlokanadan** [comment]
Hi, I am facing the same issue since a last couple of days, which was working fine all this while. Is the issue resolved for you?

**Comment by nojaf** [comment]
I had this too and remove the restricting of country.
Initially, I wanted to only allow users from my own country and after removing that check it started working for me.

**Comment by sathieshlokanadan** [comment]
@nojaf can you please clarify where you have added this country restriction?

**Comment by nojaf** [comment]
I can't tell you exactly (FB is blocked at worked) but it was somewhere in my facebook application settings or my login settings. Checkout the developer portal I'd say.

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
