### ISSUE TITLE
Marketing API rate limit

### ISSUE THREAD

**Issue by SM10855** [facebook/facebook-java-business-sdk#274]
### Which SDK version are you using?
5.0

### What's the issue?

Marketing api has rate limit.
The total time and  total cpu time are in X-App-Usage Header Value.
It  will be throttled when it's value to get at 100.
So, I delayed call API which is not to get at 100. But sometimes It return error code 1 and  message  "Please reduce the amount of data you're asking for, then retry your request".
How can I solve this problem.

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
