### ISSUE TITLE
adInsights.getFieldPublisherPlatform() was removed from auto generated class

### ISSUE THREAD

**Issue by angadbhasin** [facebook/facebook-java-business-sdk#293]
### Which SDK version are you using?

6.0.2

### What's the issue?

The `getFieldPublisherPlatform` method was removed from the auto generated class `AdsInsights.java`

### Steps/Sample code to reproduce the issue

adInsights.getFieldPublisherPlatform() should return the publisher_platform from the Ad Insights API response

#### Observed Results:

  * adInsights.getFieldPublisherPlatform() method was not found

#### Expected Results:

  * adInsights.getFieldPublisherPlatform() should return a value. ex. "Facebook"

**Comment by libbysharf** [comment]
We are a partner, and we also face this issue. It's not just this function we need but also: getFieldDevicePlatform , getFieldImpressionDevice, getFieldPlatformPosition

**Comment by GCRoberts** [comment]
I don't think this should be closed.  My research shows that this functionality is missing in both 7.0 and 8.0 of the SDK.  According to https://developers.facebook.com/docs/marketing-api/insights, v6.0 will only be available until September 28, 2020 (less than a month away!).

**Comment by angadbhasin** [comment]
I would agree with the comment above. There has been no communication from anyone at Facebook about this issue. If there is a workaround, please let us know otherwise please address the problem.

Thank you!

**Comment by GCRoberts** [comment]
Since support for v6.0 is expiring soon, we went ahead and came up with a workaround to this issue until it's addressed properly.  See my answer to this stackoverflow link for details.  https://stackoverflow.com/questions/63042491/facebook-java-business-sdk-7-0-0-lib-is-missing-adsinsights-class-member-data

**Comment by crashh** [comment]
The AdsInsights.java is missing getter and setter values for several fields.
According to the class documentation this is the place to report this:

/**
 * This class is auto-generated.
 *
 * For any issues or feature requests related to this class, please let us know
 * on github and we'll fix in our codegen framework. We'll not be able to accept
 * pull request for this class.
 *
 */

Sadly even serializing the response is not possible, as the missing Setter value is preventing the internal serialization from setting a value.
Another option to the above fix it to do manual HTTP GET requests and parse the response using JSON.
