### ISSUE TITLE
Facebook java business sdk 7.0.0 lib is missing AdsInsights class member data

### ISSUE THREAD

**Issue by alducent** [facebook/facebook-java-business-sdk#302]
Marketing API v7.0 (java lib -- facebook-java-business-sdk.7.0.0)

I recently jumped from v5.0 to v7.0 and discovered that the following fields disappeared from the AdsInsights class:
`
@SerializedName("hourly_stats_aggregated_by_advertiser_time_zone")  
private String mHourlyStatsAggregatedByAdvertiserTimeZone = null;  

@SerializedName("hourly_stats_aggregated_by_audience_time_zone")  
private String mHourlyStatsAggregatedByAudienceTimeZone = null; 

@SerializedName("product_id")  
private String mProductId = null;
`

The last lib it was present in was facebook-java-business-sdk.6.0.0 and first disappeared in version facebook-java-business-sdk.6.0.4.  I checked the change logs and found no details regarding these missing fields and it seems like an oversight. Any idea if/when these fields will return to the latest java libs?

thanks

**Comment by alducent** [comment]
Can someone from Facebook provide an answer to the question of whether the missing fields described above will in fact be restored to the java sdk libs,  or not. If the answer is yes they will, an approximate date would be very helpful. Thanks.

**Comment by alducent** [comment]
Hello Facebook. How hard can it be to simply reply? All this requires is adding a few lines to the codegen file for the AdsInsights class. Your customers depend on the this to properly server their own customers. Please take some action.

**Comment by alducent** [comment]
Could someone from facebook at least acknowledge that this is being read?

**Comment by jingping2015** [comment]
I think these fields still exist in latest SDK, like https://github.com/facebook/facebook-java-business-sdk/blob/2e7871871f7f6a350b8efc27de5197c4939925f4/src/main/java/com/facebook/ads/sdk/AdsInsights.java#L2046

**Comment by alducent** [comment]
They are  there in the EnumBreakdowns, yes, but, and the point of this issue, is that they are no longer data members.
