### ISSUE TITLE
OAuthException is_transient

### ISSUE THREAD

**Issue by alducent** [facebook/facebook-java-business-sdk#319]
### Which SDK version are you using?
Marketing API v7.0 (java libs)

### What's the issue?
api failure

### Steps/Sample code to reproduce the issue
Any api call 

#### Observed Results:
Yields the following, note that all api calls suddenly started getting these errors:

"An unexpected error has occurred. Please retry your request later.","type":"OAuthException","is_transient":true,"code":2,

#### Expected Results:

error free api call

**Comment by jingping2015** [comment]
Are you able to provide more details? Like how you use SDK to get this error ?

**Comment by alducent** [comment]
This was a case of hundreds of marketing api calls we make daily suddenly stated incurring the aforementioned error. Nothing changed in our code and our auth token was valid and our api access standing unchanged. As it turns out this was spurious and almost certainly related to FB back end servers. The problem went away after about an hour. Still, it is very disconcerting and if anyone has any insight into why this would happen it would be appreciated. Thank you.
