### ISSUE TITLE
(#10) The ad account and app id must be whitelisted

### ISSUE THREAD

**Issue by duguyue** [facebook/facebook-java-business-sdk#325]
### Which SDK version are you using?
v9.0.0
### What's the issue?
Why it throw exception when I call getAdSets() method,and it can callback data normally when I call getCampaigns and getAds methods
### Steps/Sample code to reproduce the issue
![image](https://user-images.githubusercontent.com/9762702/101765588-7a2fad00-3b1c-11eb-8fc3-468a7a846644.png)

**Comment by uwemaurer** [comment]
try this to get the ad sets request `requestAllFields().requestInstagramActorIdField(false).requestFullFunnelExplorationModeField(false)`

 Related issue https://github.com/facebook/facebook-java-business-sdk/issues/123

**Comment by duguyue** [comment]
> 
> 
> try this to get the ad sets request `requestAllFields().requestInstagramActorIdField(false).requestFullFunnelExplorationModeField(false)`
> 
> Related issue #123

Thanks,it's effective

**Comment by Sdky** [comment]
> try this to get the ad sets request `requestAllFields().requestInstagramActorIdField(false).requestFullFunnelExplorationModeField(false)`
> 
> Related issue #123

Thanks!

**Comment by galinator9000** [comment]
I'm using the Node SDK, but removing the fields instagram_actor_id and full_funnel_exploration_mode fixed this for me.

**Comment by msichterman** [comment]
> I'm using the Node SDK, but removing the fields instagram_actor_id and full_funnel_exploration_mode fixed this for me.

This was super helpful, thank you @galinator9000!
