### ISSUE TITLE
Guava Vesion too Old

### ISSUE THREAD

**Issue by ChubChen** [facebook/facebook-java-business-sdk#344]
return Futures.transform(
        executeAsyncInternal(extraParams),
        new Function<ResponseWrapper, APINodeList<AdsInsights>>() {
           public APINodeList<AdsInsights> apply(ResponseWrapper result) {
             try {
               return APIRequestGetInsights.this.parseResponse(result.getBody(), result.getHeader());
             } catch (Exception e) {
               throw new RuntimeException(e);
             }
           }
         }
      );

error

**Comment by mmorrisontx** [comment]
This is still an issue. Try compiling this project on newer versions of guava (~31) and compilation will not pass because Futures.addCallback requires three parameters now. I believe you can pass MoreExecutors.directExecutor() as the third param and that will make it happy with both 20 and 31+.

**Comment by noahrenable** [comment]
Still an issue. Any news on this?
