### ISSUE TITLE
(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v13.0.

### ISSUE THREAD

**Issue by lizhaogang** [facebook/facebook-java-business-sdk#372]
where can i get the v13.0 sdk.

please help me.

**Comment by jiahongchao** [comment]
Also have the same problem.

**Comment by vnhenryli** [comment]
have you solved the problem ?  I have the same issue. how to upgrade sdk version to v13?

**Comment by lizhaogang** [comment]
yes ,i have solved it.

**Comment by katerynao** [comment]
@lizhaogang could you please share how did you solve the issue? I'm facing the same problem

**Comment by vnhenryli** [comment]
> yes ,i have solved it.

emmm, Could you mind to share the solution? i still have this problem.the sdk publisher haven't pubulish the newest sdk yet.

**Comment by lizhaogang** [comment]
download the source code, and modify the code "v12.0" to "v13.0",then maven clean install

**Comment by vnhenryli** [comment]
> download the source code, and modify the code "v12.0" to "v13.0",then maven clean install

get it, thank you ~
