### ISSUE TITLE
v13.0.0 did not push to Maven

### ISSUE THREAD

**Issue by jchinnam** [facebook/facebook-java-business-sdk#378]
### Which SDK version are you using?

v13.0.0

### What's the issue?

The version did not push to Maven due to error.

### Steps/Sample code to reproduce the issue

See latest build: https://github.com/facebook/facebook-java-business-sdk/runs/5806712729 from https://github.com/facebook/facebook-java-business-sdk/commit/b815f20005b0f7236676793dbbaa404ac480e173

#### Observed Results:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:05 min
[INFO] Finished at: 2022-04-03T16:04:14Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project facebook-java-business-sdk: Exit code: 2 -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
```

#### Expected Results:

For the build to be available in [Maven](https://repo1.maven.org/maven2/com/facebook/business/sdk/facebook-java-business-sdk/) and to be able to use the following in our pom.xml files: 

```
<dependency>
            <groupId>com.facebook.business.sdk</groupId>
            <artifactId>facebook-java-business-sdk</artifactId>
            <version>13.0.0</version>
</dependency>
```

**Comment by danielbbvaomni** [comment]
We have just the same problem:
-Here the Maven Repository, there is no v13.0 SDK [https://mvnrepository.com/artifact/com.facebook.business.sdk/facebook-java-business-sdk](https://mvnrepository.com/artifact/com.facebook.business.sdk/facebook-java-business-sdk)
-Here the last run with the problem: [https://github.com/facebook/facebook-java-business-sdk/runs/5806712729](https://github.com/facebook/facebook-java-business-sdk/runs/5806712729)

What can we do?

**Comment by sharnikov** [comment]
Hello guys. Could you please prioritize the issue? One of our integrations is broken at our company because it requires versions 13 of API.

**Comment by roberjc** [comment]
Same issue here. We need you to release v13.

Please check your last maven build because it failed upon signing your artifact with maven-gpg-plugin:
https://github.com/facebook/facebook-java-business-sdk/runs/5806712729?check_suite_focus=true

**Comment by stcheng** [comment]
Hello. The v13.0.0 has been uploaded. https://repo1.maven.org/maven2/com/facebook/business/sdk/facebook-java-business-sdk/
It might take a while to get populated to the mvnrepository.com.
