### ISSUE TITLE
 APIRequest<APINode> or  APIRequest<AdSet> ?

### ISSUE THREAD

**Issue by wanqulou** [facebook/facebook-java-business-sdk#389]
https://github.com/facebook/facebook-java-business-sdk/blob/b815f20005b0f7236676793dbbaa404ac480e173/src/main/java/com/facebook/ads/sdk/AdAccount.java#L7312

**Comment by kirsar** [comment]
Hi, @wanqulou did you figure out proper creation flow for AdSet? 
Keeping in mind that it's not only base class returns from execute()
but there's also some breaking changes in building methods of APIRequestCreateAdSet
setBillingEvent(AdAccount.EnumBillingEvent billingEvent) vs
setBillingEvent(AdSet.EnumBillingEvent billingEvent)
?
Thanks!

**Comment by kirsar** [comment]
@wanqulou never mind, I made shallow research :)
https://github.com/facebook/facebook-business-sdk-codegen/issues/41

**Comment by wanqulou** [comment]
Thanks @kirsar
