### ISSUE TITLE
When will the v14.0 Business SDK be released?

### ISSUE THREAD

**Issue by skyjilygao** [facebook/facebook-java-business-sdk#392]
When will the v14.0 Business SDK be released?

**Comment by jubin-admaxlocal** [comment]
following...

**Comment by zhaolin2** [comment]
following...

**Comment by Kacimi-Amine** [comment]
Up

**Comment by Kacimi-Amine** [comment]
https://mvnrepository.com/artifact/com.facebook.business.sdk/facebook-java-business-sdk/14.0.0

**Comment by skyjilygao** [comment]
> https://mvnrepository.com/artifact/com.facebook.business.sdk/facebook-java-business-sdk/14.0.0

thank u
