### ISSUE TITLE
Fetching Campaign by ID throwing error: "error":{"message":"(#100) Tried accessing nonexisting field (benchmark_report_count) on node type (Campaign)","type":"OAuthException","code":100}}

### ISSUE THREAD

**Issue by gotham3** [facebook/facebook-java-business-sdk#410]
### Which SDK version are you using?
v15.0

### What's the issue?
Earlier when fetching campaign by ID returned the campaign object.
`Campaign campaign = Campaign.fetchById(facebookCampaignId, adAccount.getContext());
`

### Steps/Sample code to reproduce the issue

`Campaign campaign = Campaign.fetchById(facebookCampaignId, adAccount.getContext());
`

#### Observed Results:

  * What happened?  This could be a description, log output, etc.
 Error message:
`"error":{"message":"(#100) Tried accessing nonexisting field (benchmark_report_count) on node type (Campaign)","type":"OAuthException","code":100,"fbtrace_id":"ALioBv-AQDqKWbowOdDXPFI"}}`

#### Expected Results:

  * What did you expect to happen?
 Expected campaign object in return

**Comment by gotham3** [comment]
But we are not requesting for any specific field. We're just using this function:
`Campaign.fetchById(facebookCampaignId, adAccount.getContext())`
in the SDK there is a field called benchmark_report_count. And this same function is working in v14.0

**Comment by stcheng** [comment]
Could you check if you are using the latest version of the SDK? The field `benchmark_report_count` has been removed from the class. [link](https://github.com/facebook/facebook-java-business-sdk/commit/b95836c4ad01f07dbbf1ef0597b30f3fe9daa316#diff-fd200370027e7974900e0df95e6ab265aee304bd791f90a40336b90b722628c8L1850)

If you still encounter this issue using the latest version of SDK, please file a bug here https://developers.intern.facebook.com/support/bugs/.
