### ISSUE TITLE
Your app has been upgraded to version v17.0, please use this version or newer. This can be verified in the settings tab on the App Dashboard.

### ISSUE THREAD

**Issue by 95OldPiglet** [facebook/facebook-java-business-sdk#422]
Your app has been upgraded to version v17.0, please use this version or newer. This can be verified in the settings tab on the App Dashboard.

**Comment by xxKonstantinxx** [comment]
Same problem here, to me, this issue is also quite urgent. The JAVA SDK seems to be using the deprecated version 16 of the Marketing API. 
Has this happened in the past?
Is the JAVA SDK a safe way to use the marketing API or does it just stop working after the API version gets bumped and the old one is deprecated?

**Comment by stcheng** [comment]
The latest version of the SDK is on version 17. However, you could still use the old version of the SDK with the older version of the API. v16 will be available until Feb 2024. (https://developers.facebook.com/docs/graph-api/changelog)

**Comment by xxKonstantinxx** [comment]
> The latest version of the SDK is on version 17. However, you could still use the old version of the SDK with the older version of the API. v16 will be available until Feb 2024. (https://developers.facebook.com/docs/graph-api/changelog)
> 
> 
> 
> 

For me it is not possible to select v16 in my app settings.
Is there a planned release for the next version of the SDK?

**Comment by stcheng** [comment]
@xxKonstantinxx the release date aligns with the Graph API version release. The next release will be v18.0 and expected to be introduced in later this year.

**Comment by xxKonstantinxx** [comment]
> @xxKonstantinxx the release date aligns with the Graph API version release. The next release will be v18.0 and expected to be introduced in later this year.

Thanks for the fast reply! 
I meant the next SDK version (currently it's version 16.0.2).
The one containing the API version bump from 16 to 17

**Comment by xxKonstantinxx** [comment]
> @xxKonstantinxx the release date aligns with the Graph API version release. The next release will be v18.0 and expected to be introduced in later this year.

I'm sorry for causing any confusion.

As far as I can sell, the current version of the business SDK is version 16.0.2 (https://central.sonatype.com/artifact/com.facebook.business.sdk/facebook-java-business-sdk/16.0.2) 

this version contains the `Marketing API` version 16. 

my question was when the new SDK version (16.0.3 or so) would be released so new apps that do not support version 16 of the marketing API can be run.

**Comment by stcheng** [comment]
@xxKonstantinxx my bad. just realized that there is an issue causing the publishing of the new version failed. Will address this as soon as possible.

**Comment by dsasoft** [comment]
@stcheng seems to have solved the release 17.0.0 - THANK you!

**Comment by stcheng** [comment]
closing the issue as v17.0.0 has successfully released
