### ISSUE TITLE
i can not down this sdk

### ISSUE THREAD

**Issue by createalgorithm** [facebook/facebook-java-business-sdk#435]
#### Observed Results:

  * What happened?  This could be a description, log output, etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by createalgorithm** [comment]
<dependency>
    <groupId>com.facebook.business.sdk</groupId>
    <artifactId>facebook-java-business-sdk</artifactId>
    <version>18.0.0</version>
</dependency>

why  i can not down this  sdk?  i am china

**Comment by stcheng** [comment]
@createalgorithm are you able to access this [https://repo1.maven.org/maven2/com/facebook/business/sdk/facebook-java-business-sdk/18.0.0/facebook-java-business-sdk-18.0.0.jar](https://repo1.maven.org/maven2/com/facebook/business/sdk/facebook-java-business-sdk/18.0.0/facebook-java-business-sdk-18.0.0.jar) directly?

**Comment by createalgorithm** [comment]
> @createalgorithm are you able to access this https://repo1.maven.org/maven2/com/facebook/business/sdk/facebook-java-business-sdk/18.0.0/facebook-java-business-sdk-18.0.0.jar directly?

I can access thanks.

Why can't we directly download SDK through the central warehouse

**Comment by stcheng** [comment]
@createalgorithm you probably need to investigate the errors if there are any
