### ISSUE TITLE
adSet/reach-estimate does not exist in SDK

### ISSUE THREAD

**Issue by NickKononovichU** [facebook/facebook-java-business-sdk#439]
### Which SDK version are you using?
17.0.3 but it does not exist in 18.0.2

### What's the issue?
https://developers.facebook.com/docs/marketing-api/audiences/guides/reach-estimate/
Endpoint is not available in SDK - _**Specify an existing ad or ad set**_
```
curl -G \
  -d 'access_token=<ACCESS_TOKEN>' \
  https://graph.facebook.com/v18.0/<AD_ID>/reachestimate
```
#### Expected Results:

  * Need a way to get expected reach for adSet.

**Comment by stcheng** [comment]
@NickKononovichU could you paste a link to the endpoint on v17.0.3? I did not find the clue that this was supported.
