### ISSUE TITLE
Missing `targeting_automation` field in Targeting

### ISSUE THREAD

**Issue by fanpucheng** [facebook/facebook-java-business-sdk#451]
### Which SDK version are you using?
[v19.0.0](https://github.com/facebook/facebook-java-business-sdk/releases/tag/v19.0.0)

### What's the issue?
The ariticle published on facebook developer blog metained that Advantage+ audience API has been introduced (https://developers.facebook.com/blog/post/2024/01/23/introducing-facebook-graph-and-marketing-api-v19/). 

![image](https://github.com/facebook/facebook-java-business-sdk/assets/157341415/4020f8b8-767f-4377-b4c0-5632648a71ea)

But I cannot find the way how to set `targeting_automation` field using v19.0.0 sdk Targeting Object. I tried to set this field using json string, and I got an error like this:

```
{
  "error": {
    "message": "(#100) Unsupported targeting option: targeting_automation",
    "type": "OAuthException",
    "code": 100,
    "fbtrace_id": "AsHzy7rAC0eiVhPt05U2KnF"
  }
}
```

**Comment by stcheng** [comment]
thanks for reporting. we will have this addressed very soon.

**Comment by mkrul** [comment]
@stcheng seeing the same issue on our rails app.  Any updates on this?
