### ISSUE TITLE
Why the `VALUE_MAXIMUM ` has been replaced with `VALUE_LIFETIME` in AdsInsights.EnumDatePreset in v19.0.1?

### ISSUE THREAD

**Issue by skyjilygao** [facebook/facebook-java-business-sdk#454]
### Which SDK version are you using?
v19.0.1
### What's the issue?
Why the `VALUE_MAXIMUM ` has been replaced with `VALUE_LIFETIME` in AdsInsights.EnumDatePreset?
#### Observed Results:

  * What happened?  This could be a description, log output, etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by an-tex** [comment]
especially this being a minor release. that shouldn't break existing code.

**Comment by mariussoutier** [comment]
> What did you expect to happen?

Shouldn't happen in a minor release.

**Comment by stcheng** [comment]
Thank you for reporting this. We'll check and get back to you.

**Comment by stcheng** [comment]
This is bug and we will address this shortly.

**Comment by stcheng** [comment]
resolved in v19.0.2
