### ISSUE TITLE
Facebook Java Business SDK v20 jar is not available

### ISSUE THREAD

**Issue by movie365d** [facebook/facebook-java-business-sdk#458]
The Facebook Java Business SDK for the Marketing API version v20.0 is not available on the Maven Central Repository (https://mvnrepository.com/artifact/com.facebook.business.sdk/facebook-java-business-sdk). 

According to the Facebook Marketing API changelog documentation (https://developers.facebook.com/docs/marketing-api/marketing-api-changelog#available-marketing-api-versions), this version should be available, but it is currently missing from the repository.

**Comment by stcheng** [comment]
it's been released with some delay.
