### ISSUE TITLE
Legit phone number rejected

### ISSUE THREAD

**Issue by fluidsonic** [facebook/facebook-java-business-sdk#464]
Phone numbers are limited to 15 characters. However, we have a valid and verified (SMS/WhatsApp) phone number that's 16 characters long: `+436789012345678`. The number is anonymized but has the same number of digits and prefix.

https://github.com/facebook/facebook-java-business-sdk/blob/c35f3e0cc41e30cd28e8148b9dec695aaf9afcf5/src/main/java/com/facebook/ads/utils/ServerSideApiUtil.java#L147-L157

**Comment by stcheng** [comment]
Thank you. We will update the if statement.

**Comment by stcheng** [comment]
resolved.
