### ISSUE TITLE
[Java SDK] Facebook partnerdata API

### ISSUE THREAD

**Issue by nemccarthy** [facebook/facebook-java-business-sdk#48]
Hi guys,

This SDK is really handy however its missing one big feature, if we want to upload data to the `/act_<AD_ACCOUNT_ID>/partnerdata` endpoint its not supported. Are there plans to add this one in? 

https://developers.facebook.com/docs/marketing-api/data-partners-api

Thanks!

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
