### ISSUE TITLE
Retrieve Saved Audience

### ISSUE THREAD

**Issue by sang-d** [facebook/facebook-java-business-sdk#58]
I can retrieve customaudiences from ad_account
/act_{ad_account_id}/customaudiences

But it doesn't include saved audience (the one contain geolocation, gender, interest, locale).
Pls advise how to retrieve this data

![screen shot 2016-11-04 at 11 02 12 am](https://cloud.githubusercontent.com/assets/11723598/19994241/ca279880-a27e-11e6-803f-29f22e8faa81.png)

**Comment by KManiKumarReddy** [comment]
There is no edge to retrieve saved audiences from ad accounts edge, it'll be hight appreciated if it's added in the next version

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
