### ISSUE TITLE
NullPointerException throws while trying to access /me/businesses

### ISSUE THREAD

**Issue by chrisptang** [facebook/facebook-java-business-sdk#60]
Hi ,

I'm using java sdk v0.4. It seems like there has no method to allow me to list all businesses belongs to the user. So I just use the following code as alternative:
`APIRequest<Business> request = new APIRequest<Business>(context, "me", "/businesses", "GET",Business.getParser());`
The API response correctly as expect:
`{"data":[{"name":"Alibaba advertising","id":"7349984ACCOUNTID72"}],"paging":{"next":"https://graph.facebook.com/v2.8/130101310692072/businesses?access_token=MY_ACCESS_TOKEN&limit=25&offset=25&__after_id=enc_AdCRaZCZAD9ZAbIQDB7lYwCoNqAaNcqRbEWaRPZCHaPS8eSxQ11pUw7nHnOC1ZCBGm6moP4vaYSOp3D132M032XHZBUG3P"}}`

But this line of code throws a NullPointerException which I think it shouldn't:
`JsonObject paging = obj.get("paging").getAsJsonObject().get("cursors").getAsJsonObject();`
The above code can be found at Business.java, line 163.

Would you be kindly to take a look? Thanks a lot.
-Peng

**Comment by lintaocui** [comment]
Hi, @chrisptang thank you for reporting the bug. We have confirmed the bug exists and are working on the fix now. Please be patient.

**Comment by chrisptang** [comment]
Hi @lintaocui thanks for the quick response.
Would you plan to fix it in next build?

**Comment by shihch** [comment]
The same problem still exists in v2.10 in AdAccount.parseResponse(..)
