### ISSUE TITLE
APIRequestGetAdVideos miss values in FIELDS constant

### ISSUE THREAD

**Issue by nicolasdalsass** [facebook/facebook-java-business-sdk#70]
This [lack](https://github.com/facebook/facebook-java-ads-sdk/blob/master/src/main/java/com/facebook/ads/sdk/AdAccount.java#L5532) makes the call to APIRequestGetAdVideos.requestAllFields() actually request nothing.

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK bugs!

This is indeed an issue we're working on; Videos have lots of fields and we haven't really figured out what fields should be default and what should not be.

In the meantime, you can use [requestFields](https://github.com/facebook/facebook-java-ads-sdk/blob/master/src/main/java/com/facebook/ads/sdk/AdAccount.java#L5580) to get the fields you want.

Thanks!

**Comment by manssa01** [comment]
Hello how can I use my code to retrieve the "total_video_views" metric:
import com.facebook.ads.sdk.APIContext;
import com.facebook.ads.sdk.APIException;
import com.facebook.ads.sdk.APINodeList;
import com.facebook.ads.sdk.APIRequest;
import com.facebook.ads.sdk.Ad;
import com.facebook.ads.sdk.AdAccount;
import com.facebook.ads.sdk.AdSet;
import com.facebook.ads.sdk.AdsActionStats;
import com.facebook.ads.sdk.AdsInsights;
import com.facebook.ads.sdk.Campaign;
import com.restfb.Connection;
import com.restfb.json.JsonObject;
import com.restfb.types.Insight;
import java.util.Iterator;
import java.util.List;

/**
*

@author manssa01
*/

public static void main(String[] args) throws APIException {
APIContext("********************************************************************************************");
try {
APIRequest request = new APIRequest<>(context, "me", "/adaccounts", "GET", AdAccount.getParser());
APINodeList accounts = (APINodeList)(request.execute());
for (AdAccount account : accounts) {
APINodeList campaigns = new AdAccount( account.getId(), context).getCampaigns().requestAllFields()
.execute();
for (Campaign campaign : campaigns) {
APINodeList adSets = new Campaign( campaign.getId(), context).getAdSets().requestAllFields()
.execute();
for (AdSet adset : adSets) {

      APINodeList<Ad> ads = new AdSet( adset.getId(), context).getAds().requestAllFields()
.execute();

      for (Ad ad:ads) {
           APINodeList<AdsInsights> adInsights = new Ad(ad.getId(), context).getInsights().requestField("what to write here")
.execute();
for (AdsInsights adInsight : adInsights) {

Ad.APIRequestGetInsightsAsync insightsAsync = new Ad(adId, context).getInsightsAsync();
// AdReportRun report = insightsAsync
//	.requestField("account_name")
//	.requestField("impressions")
// .requestField("spend")
// .requestField("reach")
// .requestField("total_actions")
//	.requestField("clicks")
////	.requestField("total_video_views")
////	.requestField("cpc")
////	.requestField("cost_per_action_type")
////	.requestField("cost_per_unique_click")
////	.requestField("cpm")
// .requestField("video_10_sec_watched_actions")
// .requestField("video_30_sec_watched_actions")
// .requestField("video_p100_watched_actions")
// .requestField("video_p95_watched_actions")
// .requestField("video_p75_watched_actions")
// .requestField("video_p50_watched_actions")
// .requestField("video_p25_watched_actions")
//	.execute()
//	.head();
// while (report.fetch().getFieldAsyncPercentCompletion() != 100) {
//	try {
//	Thread.sleep(6000);
//	} catch (InterruptedException e) {
//
//	}



            }
            }
           
      }
    }  
    }
} catch (Exception e) {
e.printStackTrace();
}
}

}

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
