### ISSUE TITLE
Audience Insights API

### ISSUE THREAD

**Issue by siddharthsa** [facebook/facebook-java-business-sdk#73]
Hey Facebook Team,
We are very much interested to use the below mentioned API to get insights on our custom audience which we upload to run our marketing campaigns. I understand that currently it is not being supported in the SDK. I would like to know the rough timelines, when we can expect this API to be open for general use.
https://developers.facebook.com/docs/graph-api/reference/audience-insights-query/

**Comment by sergeymishin** [comment]
Really need Audience Insights API too!
