### ISSUE TITLE
AdCreative can't set the title/body

### ISSUE THREAD

**Issue by zhengzhiyuan** [facebook/facebook-java-business-sdk#90]
hi fb dev term

i set title/body of AdCreative through below api. But i can't see the corresponding information in the Input box of Headline/Text.

api : 
AdAccount.createAdCreative().setBody(body).setTitle(title)

**Comment by IG16** [comment]
Hello, 
I think my issues relates to this thread.
Using Facebook Marketing API with Java SDK, I would like to create a simple Facebook Ad. In object AdCreativeLinkData I can call: .setFieldMessage("Ad Text") and .setFieldDescription("News Feed Description") but I am unable to find the correct call to set the Headline for the ad creative. What function on which object do I need to call to set the Headline field?

**Comment by Chream** [comment]
bumb. Having the same issue.
